// Floor themes: the opening zone is 100 floors, every zone after it is 200.
//
// Generated by the local Qwen model, then corrected. It got the structure and the
// narrative arc right on the first try (basement -> dungeon -> forest -> ... -> zenith)
// and every hex string was well formed. What it did NOT keep was the readability
// constraint it was explicitly given: FIVE of the twelve shipped platforms or text that
// were near-invisible against their own sky. tools/test-themes.mjs enforces it now --
// it is the only thing that does, and it fails the build rather than warning.
//
// DUNGEON's greys were later recoloured by hand, cooler and darker, so warm bone reads
// against them: a crypt band needs its skeletons to be visible and #e8dcbf on the old
// #aaaaaa was 1.67:1.
//
// DOWNTOWN was called VILLAGE until 2026-09-23, when the user renamed it (the street of
// tall lit house fronts at night). A first pass took the request for a regrouping of the
// music and left the name alone. The name is the key every per-zone table and module is
// found by, so it changed everywhere at once; FORMER_NAMES below is the one place the old
// name lives on.

import { FLOORS_PER_THEME, FIRST_THEME_FLOORS } from './constants.js';

export const THEMES = [
  { name:"BASEMENT", sky:["#1a1020","#2d1b3d"], platTop:"#cc8855", platBody:"#996633", platEdge:"#664422", accent:"#ffaa33", particle:"#ffcc88", bgFar:"#241830", bgNear:"#332244", text:"#ffe099" },
  { name:"DUNGEON", sky:["#151525","#252535"], platTop:"#8e94a6", platBody:"#5f6472", platEdge:"#43445c", accent:"#ffff00", particle:"#ffffff", bgFar:"#1a1a30", bgNear:"#2a2a40", text:"#ffffcc" },
  { name:"FOREST", sky:["#2f7a34","#1d5424"], platTop:"#e8bb63", platBody:"#a8752f", platEdge:"#6b4a1c", accent:"#ff3355", particle:"#7dff5a", bgFar:"#276a2c", bgNear:"#17441e", text:"#fff3c4" },
  { name:"SWAMP", sky:["#556633","#334422"], platTop:"#cc6644", platBody:"#994433", platEdge:"#662222", accent:"#ffcc00", particle:"#88ff44", bgFar:"#667744", bgNear:"#445533", text:"#ffff44" },
  { name:"DOWNTOWN", sky:["#3a3050","#544a6a"], platTop:"#cc8855", platBody:"#aa6633", platEdge:"#774422", accent:"#ff8a5c", particle:"#ffc4a8", bgFar:"#453a5e", bgNear:"#5c5078", text:"#ffe9d6" },
  { name:"CITADEL", sky:["#566f9c","#3d5480"], platTop:"#ffffff", platBody:"#c3cfe0", platEdge:"#8f9cb5", accent:"#ffcc00", particle:"#ffffff", bgFar:"#4a608a", bgNear:"#33476f", text:"#ffd21f" },
  { name:"STORM", sky:["#332244","#554466"], platTop:"#ffff99", platBody:"#cccc66", platEdge:"#999933", accent:"#cc66ff", particle:"#ffffcc", bgFar:"#443355", bgNear:"#665577", text:"#ffe066" },
  { name:"ABYSS", sky:["#100a1c","#1e1430"], platTop:"#cc88ff", platBody:"#9966cc", platEdge:"#664499", accent:"#aa44ff", particle:"#ffccff", bgFar:"#1c1238", bgNear:"#2a1c48", text:"#cc44ff" },
  { name:"NEBULA", sky:["#1c0a30","#3f1a5e"], platTop:"#dcbef4", platBody:"#8862cc", platEdge:"#54399a", accent:"#ff44cc", particle:"#c9a0f0", bgFar:"#2a1246", bgNear:"#4a1f6b", text:"#a8e4ff" },
  { name:"COSMOS", sky:["#001133","#002244"], platTop:"#aabbcc", platBody:"#8899aa", platEdge:"#667788", accent:"#ffffff", particle:"#ccddff", bgFar:"#112255", bgNear:"#223366", text:"#88aacc" },
  { name:"STARFIELD", sky:["#002222","#004444"], platTop:"#00aa55", platBody:"#008844", platEdge:"#006633", accent:"#ff4400", particle:"#00dd66", bgFar:"#113344", bgNear:"#225566", text:"#00ff88" },
  { name:"ZENITH", sky:["#54648a","#8b9fc0"], platTop:"#ffe9a0", platBody:"#c9a95e", platEdge:"#6e5730", accent:"#ffd24a", particle:"#fff4d0", bgFar:"#465578", bgNear:"#66789c", text:"#ffffff" }
];

/**
 * What a renamed zone was called before. Two things still need the old name. The painters
 * that hash the zone's name into their random stream (the side walls' wallRng, the HUD
 * skin's grain and specks) must go on hashing the name the art was drawn under -- seeded by
 * DOWNTOWN, every patch on its walls and speck on its HUD moved (35,000 px a frame), and a
 * rename is not a repaint: see artSeed. And a tool reading an older commit's generated
 * modules (tools/diff-platforms.mjs) finds the zone there under its old key.
 */
export const FORMER_NAMES = { DOWNTOWN: 'VILLAGE' };

/** The name a zone's seeded art was painted under: its first name. */
export function artSeed(name) { return FORMER_NAMES[name] || name; }

import { mulberry32 } from '../core/rng.js';

// Past the twelfth band the tower does not stop and does not simply repeat. Each
// further cycle of twelve is a fresh deterministic shuffle, so the order is different
// every time round -- and the run can go forever. The shuffle is seeded by the cycle
// number alone, not the run's seed, so every run meets the zones in the same order.
const orderCache = new Map();

/** Floors in one full pass through every theme: 100 + 11 * 200 = 2300. */
export const CYCLE_FLOORS = FIRST_THEME_FLOORS + (THEMES.length - 1) * FLOORS_PER_THEME;

function orderForCycle(cycle) {
  let o = orderCache.get(cycle);
  if (o) return o;
  o = THEMES.map((_, i) => i);
  const r = mulberry32((cycle * 2654435761 + 0x9e37) >>> 0);
  for (let i = o.length - 1; i > 0; i--) {
    const j = Math.floor(r() * (i + 1));
    [o[i], o[j]] = [o[j], o[i]];
  }
  // Never open a cycle with the band that closed the previous one -- a theme change
  // that changes nothing reads as a bug.
  const prevLast = cycle === 1
    ? THEMES.length - 1
    : orderForCycle(cycle - 1)[THEMES.length - 1];
  if (o[0] === prevLast) [o[0], o[1]] = [o[1], o[0]];
  orderCache.set(cycle, o);
  return o;
}

/**
 * Which zone a floor is in, how far into it, and how long that zone is.
 *
 * Zones are NOT uniform. The first is half length so the first change arrives early and
 * a run establishes its rhythm before the tower re-skins itself; every zone after it is
 * full length. That is also what makes the numbers land where they were asked to: with
 * twelve themes the last zone begins at 2100 and the tower loops at 2300.
 *
 * Everything that used to divide by a single FLOORS_PER_THEME goes through this, because
 * a modulo cannot describe a schedule whose first term is a different size and silently
 * puts every boundary after the first one in the wrong place.
 */
export function bandFor(floor) {
  const f = Math.max(0, floor);
  const cycle = Math.floor(f / CYCLE_FLOORS);
  const r = f - cycle * CYCLE_FLOORS;
  if (r < FIRST_THEME_FLOORS) return { cycle, band: 0, into: r, len: FIRST_THEME_FLOORS };
  const b = 1 + Math.floor((r - FIRST_THEME_FLOORS) / FLOORS_PER_THEME);
  return {
    cycle,
    band: b,
    into: (r - FIRST_THEME_FLOORS) % FLOORS_PER_THEME,
    len: FLOORS_PER_THEME,
  };
}

export function themeIndexFor(floor) {
  const { cycle, band } = bandFor(floor);
  if (cycle === 0) return band;
  return orderForCycle(cycle)[band];
}

export function themeFor(floor) {
  return THEMES[themeIndexFor(floor)];
}
