// GENERATED by tools/import-backgrounds.mjs -- do not edit by hand.
//
//   node tools/import-backgrounds.mjs --emit > src/render/bgart.js
//
// The artist's background tiles that exist in assets/backgrounds/, by zone and layer.
// Anything not listed is painted by the zone's code painter (src/render/bgpaint/).
// Listing only what exists is what keeps the game from requesting a missing file.
// The *Wrap pairs are [left/right, top/bottom] mean edge differences; under 10 is
// seamless, over 30 is a visible seam.

export const BG_TILE = 256;

export const BG_FILES = {
};

