// The six companions.
//
// The art is IMPORTED -- one module per companion under ./companions/, generated by
// tools/import-sprite.mjs from the reference sheets in Companions/. Ten poses each, in
// the order COMP_POSE_NAMES lists them.
//
// Two things stood here before. First six hand-typed 16x22 grids sharing one
// bell-shaped body -- no arms, no legs, none of the gear their names promise. Then a
// procedural figure builder, which got them as far as "recognisable" and no further:
// every attempt to push it beyond that produced something that was rejected on sight.
// Both are gone. Drawn art beats generated art, and the pipeline that proved it on the
// Duke is one command per sheet.
//
// EACH COMPANION HAS ITS OWN SIZE, and that is the point. The sheets were drawn at six
// different scales, so they are imported by matching their IDLE heights rather than
// their tallest frames -- scale by the tallest and the halfling comes out exactly as
// tall as the shield-maiden. The cell is 164 art pixels tall for all six because that
// is what the biggest leap needs; the width is whatever the character is. The exact
// command for each is in the head of its module.

import * as PILGRIM from './companions/pilgrim.js';
import * as ARCHER from './companions/archer.js';
import * as DELVER from './companions/delver.js';
import * as RANGER from './companions/ranger.js';
import * as HALFLING from './companions/halfling.js';
import * as MAIDEN from './companions/maiden.js';
import { PX } from '../game/constants.js';
import { newCanvas } from './canvases.js';

const ART = {
  pilgrim: PILGRIM,
  archer: ARCHER,
  delver: DELVER,
  ranger: RANGER,
  halfling: HALFLING,
  maiden: MAIDEN,
};

/**
 * The ten poses, in the order they appear on every sheet.
 *
 * Reading order -- rows top to bottom, left to right within a row: two standing, three
 * running, the rise, the descent, the landing crouch, the tumble, the slip.
 */
export const COMP_POSE_NAMES = [
  'idle0', 'idle1', 'run0', 'run1', 'run2', 'jump', 'fall', 'land', 'tumble', 'slip',
];

export const COMPANION_IDS = ['pilgrim', 'archer', 'delver', 'ranger', 'halfling', 'maiden'];

export const COMPANION_NAMES = {
  pilgrim:  'THE GREY PILGRIM',
  archer:   'THE LONGSHOT',
  delver:   'THE STONE-DELVER',
  ranger:   'THE HOODED KING',
  halfling: 'THE SMALL ONE',
  maiden:   'THE SHIELD-MAIDEN',
};

// Each companion's register, in semitones: where their babble sits when they speak
// (SFX.speak). It was also a key each lifted the whole piece into while they climbed with
// you -- fourths and fifths up, a third or a whole step down -- until 2026-09-24: joining
// and slipping at random moments, they moved the music mid-phrase, and now they do not.
export const COMPANION_KEY = {
  pilgrim:  0,   // E  -- home
  archer:   5,   // A  -- up a fourth
  delver:  -3,   // C# -- down a minor third, heavier
  ranger:   7,   // B  -- up a fifth, brightest
  halfling: 2,   // F# -- up a whole step
  maiden:  -5,   // B below -- down a fourth, grand
};

export function compArt(id) {
  return ART[id] || ART.pilgrim;
}

/**
 * One companion's size in WORLD units.
 *
 * DERIVED from its art, never declared. One art pixel must be one screen pixel, so the
 * world size is the art size over PX and there is nothing left to choose. The old
 * constants were 16 x 22 for everybody and were used as BOTH the art size and the world
 * size -- which is exactly why every companion was four times chunkier than the Duke
 * standing next to them, and why no test noticed.
 */
export function compSize(id) {
  const a = compArt(id);
  return { w: a.SPR_W / PX, h: a.SPR_H / PX };
}

const cache = new Map();

/** One canvas per companion PER POSE, rasterised on first use and kept. */
export function canvasFor(id, pose = 'idle0') {
  const key = id + ':' + pose;
  let c = cache.get(key);
  if (c) return c;

  const a = compArt(id);
  const i = Math.max(0, COMP_POSE_NAMES.indexOf(pose));
  const rows = a.FRAMES[i] || a.FRAMES[0];

  let g;
  ({ c, g } = newCanvas(a.SPR_W, a.SPR_H));
  for (let y = 0; y < a.SPR_H; y++) {
    const row = rows[y] || '';
    let x = 0;
    while (x < row.length) {
      const k = row[x];
      if (!k || k === '.') { x++; continue; }
      let run = 1;
      while (x + run < row.length && row[x + run] === k) run++;
      g.fillStyle = a.PAL[k] || '#ff00ff';
      g.fillRect(x, y, run, 1);
      x += run;
    }
  }
  cache.set(key, c);
  return c;
}

/**
 * The poses a companion is drawn STANDING IN: the two idles, the three strides and the
 * landing crouch. Every pose the renderer picks while its feet are on a ledge.
 *
 * The other four are in the air -- the rise, the descent, the tumble and the slip -- and
 * there is no ledge under them to be level with, so they are anchored where the importer
 * left them.
 */
export const COMP_GROUND_POSES = new Set(['idle0', 'idle1', 'run0', 'run1', 'run2', 'land']);

/**
 * The row each companion's lowest BOOT pixel is on, per standing pose.
 *
 * The importer bottom-aligns every cell on its lowest ink, and for five of the six that
 * lowest ink is a boot: their soles are the cell bottom and hanging the cell from the
 * ledge stands them on it. The PILGRIM plants a STAFF, and in idle0, idle1 and land its
 * tip is one art pixel below his soles -- so he hung from the staff and his boots floated
 * a screen pixel over every ledge at zoom 1 and 1.25, two at 1.5 and above, in both
 * facings, for as long as he has been in the game. On a grassy ledge nobody saw it. On
 * DOWNTOWN's flat deck it is a line of sky under a standing man.
 *
 * WHY THESE ARE WRITTEN DOWN RATHER THAN COMPUTED. The Duke's boots are found by a rule
 * (bootDrop in sprites.js: his sabatons are steel and his shield is gold and crimson, so
 * the colours vote). Six companions drawn on six sheets share no palette to vote with,
 * and the obvious fallback -- take the lowest row WIDE enough to be a footprint -- cannot
 * work here: the pilgrim's staff foot is 1 px wide in idle0 and land and 5 px in idle1,
 * while a real toe is 2 px in the archer's idle1, the maiden's land and the pilgrim's own
 * run1. Any threshold that drops the 5 px staff drops those toes with it.
 *
 * So a person read them off x8 crops of the imported cells --
 * `node tools/shot-compfeet.mjs --art` -- and tools/test-companions.mjs holds the anchor
 * to these rows. A re-import that moves anybody's feet fails there, on purpose: look at
 * the new crops and write down what you see, rather than letting the number drift.
 */
export const COMP_BOOT_ROW = {
  pilgrim:  { idle0: 162, idle1: 162, run0: 163, run1: 163, run2: 163, land: 162 },
  archer:   { idle0: 163, idle1: 163, run0: 163, run1: 163, run2: 163, land: 163 },
  delver:   { idle0: 163, idle1: 163, run0: 163, run1: 163, run2: 163, land: 163 },
  ranger:   { idle0: 163, idle1: 163, run0: 163, run1: 163, run2: 163, land: 163 },
  halfling: { idle0: 163, idle1: 163, run0: 163, run1: 163, run2: 163, land: 163 },
  maiden:   { idle0: 163, idle1: 163, run0: 163, run1: 163, run2: 163, land: 163 },
};

/**
 * How far a standing pose must be LOWERED, in world units, so it stands on its boots
 * instead of on whatever the importer found lowest. Derived from the measured boot row,
 * never declared: one art pixel is 1/PX world units.
 */
export const COMP_FOOT_DROP = Object.fromEntries(COMPANION_IDS.map((id) => {
  const a = compArt(id);
  const rows = COMP_BOOT_ROW[id] || {};
  return [id, Object.fromEntries(COMP_POSE_NAMES.map((p) => [p,
    COMP_GROUND_POSES.has(p) && rows[p] !== undefined ? (a.SPR_H - 1 - rows[p]) / PX : 0]))];
}));

export function compFootDrop(id, pose) {
  const d = COMP_FOOT_DROP[id];
  return (d && d[pose]) || 0;
}

/**
 * Draw one companion with its FEET on `by`, centred on `cx`, in world units.
 *
 * The caller has already flipped the world's y axis for blitting (ctx.scale(1, -1)), so
 * the cell's bottom edge is at -by, and lowering it onto the boots is an addition here
 * and a subtraction in world y. It used to be drawn straight at -by with no drop at all,
 * which is the whole of the pilgrim's hover: nothing in this path asked where his feet
 * were, only where his ink stopped.
 *
 * `spin` is the tumble away after a slip -- quarter turns about the cell's centre, like
 * the player's own fall. No drop there: a companion cartwheeling through the air has
 * nothing to stand on, and dropping the cell would make the pivot wander. It is null when
 * they are not tumbling, rather than 0, because a tumble PASSES THROUGH 0 four times a
 * turn and the upright quarter of a cartwheel must still be drawn the tumbling way: the
 * facing is not flipped in it, and it pivots on the cell's centre.
 */
export function drawCompanion(ctx, id, pose, cx, by, flip = false, spin = null) {
  const img = canvasFor(id, pose);
  const { w: CW, h: CH } = compSize(id);
  if (spin !== null) {
    const q = ((Math.round(spin) % 4) + 4) % 4;
    ctx.save();
    ctx.translate(cx, -by - CH / 2);
    ctx.rotate((q * Math.PI) / 2);
    ctx.drawImage(img, 0, 0, img.width, img.height, -CW / 2, -CH / 2, CW, CH);
    ctx.restore();
    return;
  }
  const bottom = -by + compFootDrop(id, pose);
  if (flip) {
    ctx.save();
    ctx.translate(cx, 0);
    ctx.scale(-1, 1);
    ctx.drawImage(img, 0, 0, img.width, img.height, -CW / 2, bottom - CH, CW, CH);
    ctx.restore();
  } else {
    ctx.drawImage(img, 0, 0, img.width, img.height, cx - CW / 2, bottom - CH, CW, CH);
  }
}

export function resetCompanionCache() { cache.clear(); }
