// GENERATED by tools/import-decor.mjs -- do not edit by hand.
//
//   node tools/import-decor.mjs --emit > src/render/decorart.js
//
// The artist's furniture sprites that exist in assets/decor/ and passed the importer's
// checks, by zone and element key. Anything not listed is painted by its zone module
// (src/render/decorpaint/). Listing only what exists is what keeps the game from
// requesting a missing file.

export const DECOR_FILES = {
};
