// The title emblem: the arms of the Grand Duchy, as the logo.
//
// It sits BETWEEN the two words of the title -- DUKE [shield] VYTIS -- because that is
// the one place a device can go without covering a letter. drawTitle() in screens.js owns
// the box, the words and the shield together, so they cannot disagree about where they
// are, and the emblem's width is part of that arithmetic rather than a thing laid on top
// and hoped for.
//
// --- where the art comes from ------------------------------------------------
//
// IMPORTED. src/render/shieldart.js is generated by tools/import-shield.mjs from the
// artist's illustration, area-averaged down to EMB_W x EMB_H and snapped to a palette of
// its own; this file only places it.
//
// It used to be BUILT here: a heater outline computed from an arc, ring depths found by
// erosion, a rim painted from those, and two swords struck into the grid as chunky lines.
// Two hundred and fifty lines, and the right answer for as long as the only shield in the
// project was one I could compute. It is not the right answer once somebody draws one.
//
// --- resolution --------------------------------------------------------------
//
// Drawn at 1/PX world units per emblem pixel -- the same relationship the character uses
// (SPR_W is BODY_W * PX). One emblem pixel is then exactly one pixel of the backing store
// and nothing here is ever resampled. At any other size the gold rim mushes into the
// field, which is why the character sprite carries that same invariant in a test.

import { PX } from '../game/constants.js';
import * as ART from './shieldart.js';

/** Every colour the imported art uses. Keyed in digits and punctuation -- see the import. */
export const INK = ART.PAL;

export const EMB_W = ART.EMB_W, EMB_H = ART.EMB_H;   // emblem pixels
// World units. Divided by PX, not by a literal: the invariant is "one emblem pixel is one
// backing-store pixel", and PX is what makes that true.
export const EMB_WW = EMB_W / PX;
export const EMB_WH = EMB_H / PX;

/** The logo as a grid of palette keys. */
function build() {
  return ART.EMBLEM.map((row) => [...row]);
}

let baked = null;

/** The emblem as a canvas, one emblem pixel per canvas pixel. Built once. */
export function emblemCanvas() {
  if (baked) return baked;
  const art = build();
  const c = document.createElement('canvas');
  c.width = EMB_W; c.height = EMB_H;
  const g = c.getContext('2d');
  for (let y = 0; y < EMB_H; y++) {
    let x = 0;
    while (x < EMB_W) {
      const ch = art[y][x];
      if (ch === '.') { x++; continue; }
      let run = 1;
      while (x + run < EMB_W && art[y][x + run] === ch) run++;
      const col = INK[ch];
      if (col) { g.fillStyle = col; g.fillRect(x, y, run, 1); }
      x += run;
    }
  }
  baked = c;
  return c;
}

/** The raw grid and its colours, for tests and for baking the application icon. */
export function emblemArt() { return build(); }
export function emblemInk() { return INK; }

export function resetEmblemCache() { baked = null; }

/**
 * Draw the emblem centred on (cx, cy) in WORLD units.
 *
 * The destination size is fixed at the emblem's pixel size over PX and is deliberately
 * not a parameter: any other number resamples it.
 */
export function drawEmblem(ctx, cx, cy) {
  const c = emblemCanvas();
  ctx.drawImage(c, Math.round(cx - EMB_WW / 2), Math.round(cy - EMB_WH / 2), EMB_WW, EMB_WH);
}
