// DUKE VYTIS - the climber.
//
// A crowned Lithuanian grand duke in full plate: tall gold crown, an enormous forked
// auburn beard, steel harness under a deep blue tabard with a gold cross, a red heater
// shield charged with the Vytis -- the armoured horseman of the Grand Duchy's arms, sword
// raised, on a white horse -- and a longsword. "Vytis" is the old name for the
// arms of Lithuania and it means THE CHASE, which for a game about being chased up a
// tower was too good to pass up.
//
// --- where the art comes from ------------------------------------------------
//
// It is IMPORTED, not authored here. src/render/vytisart.js is generated by
// tools/import-sprite.mjs from the artist's reference sheet, and this file is only the
// engine that poses and draws it.
//
// That replaced a procedural system: hand-written ASCII grids for the head and torso,
// with arms and legs rasterised at bake time from joint angles. The procedure was the
// right answer while the art was mine, because a new pose cost two numbers instead of a
// new drawing. It is the wrong answer now -- the art is drawn by somebody who can draw,
// and the only job here is to get their pixels on screen unaltered.
//
// --- resolution ---------------------------------------------------------------
//
// SPR_W x SPR_H are the sheet's own dimensions and BODY is those divided by PX, so one
// art pixel is exactly one backing-store pixel. That identity is the whole reason he
// looks like the reference rather than a resample of it, and test-sprites.mjs asserts
// it.
//
// The cell is 252x212 art pixels, 63x53 world units, and he stands 177 pixels -- about
// 44 units -- in idle0. That is a decision, not arithmetic: he was 77 pixels and 19.25
// units once, sized to fit the 23-unit gap between floors, and was made this big on
// purpose because he read as too small to be the hero. He draws over the ledge above
// him now. His COLLISION box is a separate 16x22 (PLAYER_W, PLAYER_H), which is why the
// sprite can change size without a single jump changing.
//
// The sheet was not pixel art when it arrived: a high-resolution illustration in a
// pixel-art style, tens of thousands of colours, anti-aliased throughout. The importer
// resamples it and snaps every colour to a 36-entry palette built from the sheet, which
// is what turns a gradient back into an edge. The exact command is in the head of
// vytisart.js; see tools/import-sprite.mjs.

import { SPR_W, SPR_H, PAL, FRAMES as RAW_ART } from './vytisart.js';

// THE SHIELD IS DRAWN, NOT STAMPED.
//
// Every pose on this sheet is drawn with the arms of the Grand Duchy on the shield in his
// hand, at the angle that pose holds it. That retires a whole machine: shieldstamp.js used
// to find the red field in each cell, measure its box and draw a computed heater into it,
// because no sheet before this one had the right device on it. Finding a shape by its
// colour and painting over it is a thing you do when you have no other choice, and it cost
// what that costs -- his beard is the same family of reds, so for a while three poses had a
// coat of arms stamped over his face.
//
// What is left of that file is its MEASURING half, now tools/shieldfind.mjs. Nothing in
// the game uses it -- this file imports nothing from it -- only tools/shot-shields.mjs,
// which crops the shield out of every cell, and tools/test-sprites.mjs, which checks each
// cell that should carry one does. Nothing paints any more.
const ART = RAW_ART;

// One palette now, the character's own. The stamp used to add six colours the sheet did
// not contain -- starting with white, because an argent horse rendered in the nearest
// available colour is a beige horse. The drawing brings its own white.
const INKS = PAL;

import { PX, CUT_OUTLINE_V, LIMB_MATCH, PLATE_MIN, PLATE_STEEL } from '../game/constants.js';
import { newCanvas } from './canvases.js';

export { SPR_W, SPR_H, PAL };

export const BODY_W = SPR_W / PX;   // world units he occupies
export const BODY_H = SPR_H / PX;

// --- which drawing each pose uses ---------------------------------------------
//
// The sheet gives eighteen drawings, cells 0 to 17, all facing right or front. `art`
// indexes them.
//
// Every pose the game asks for now has real art behind it. The airborne, landing and
// death poses are no longer squashed walk frames: there is a drawn scream with the crown
// coming off, a drawn concussion with the eyes crossed out, and a drawn splat with the
// crown lying beside him.
//
// Two pairs of poses share a drawing. `dazed` and `splat` are both cell 15, him lying
// where he landed; the splat is never drawn whole -- the renderer takes him apart into
// the pieces in 16 and 17 instead (drawSplatter) -- so it needs no drawing of its own.
// `backfall` and `backfallHeld` are both cell 14, the second reassembled at load (see
// below). Nothing else doubles up. On an earlier sheet the shared pair was `tuck` and
// `land`, both the deep crouch; each has its own drawing now, 13 and 11.
const POSE = {
  // THE IDLE, five drawings: sword up, down to the left, both low and square on, down
  // to the right, up again. A flourish, not a pose held with a bob on it -- and the
  // blade is in frame the whole way round, which took three rewrites of this cycle to
  // achieve because the sheet it replaces had no armed front drawing that was not its
  // own death frame.
  idle0: { art: 2 },        // square on, both hands low -- the one he returns to
  idle1: { art: 1 },        // sword swung down to his left
  idle2: { art: 0 },        // ...and up
  idle3: { art: 3 },        // down to his right
  idle4: { art: 4 },        // ...and up

  run0: { art: 5 },
  run1: { art: 6 },
  run2: { art: 7 },

  jump: { art: 9 },         // rising, sword up
  jumpFast: { art: 8 },     // committed, blade thrown back
  fall: { art: 10 },        // descending, reaching
  fallFast: { art: 12 },    // braced, thrown forward into the drop
  tuck: { art: 13 },        // the ball -- only ever drawn rotated
  land: { art: 11 },        // absorbing the hit, compact over his knees
  backfall: { art: 14 },    // the death plunge: screaming, crown and gear coming off
  // THE SAME PLUNGE, HELD TOGETHER, and the one the fall actually draws.
  //
  // The drawing above has his crown, shield and sword already flying off him, which is
  // a fine single frame and wrong for a fall that lasts two seconds: tumbling down the
  // shaft in quarter turns, he read as coming apart before anything had hit him, and
  // then came apart AGAIN at the bottom. He stays in one piece until he lands. Baked
  // at load from cell 14 by assembleHeld() below -- the crown seated back on his head,
  // the shield and sword pulled in against him -- so it is DERIVED, and flagged as such
  // until the sheet has a drawing of it.
  backfallHeld: { art: 14, hold: true, derived: true },
  // A man who has just fallen the height of a tower is not standing up. He lies where
  // he landed, crown beside him.
  dazed: { art: 15 },
  // Above SPLAT_FLOOR he does not land in one piece. 16 and 17 are him in PIECES,
  // DRAWN -- a torso, a head, arms, legs, his sword and his shield. The renderer used
  // to cut a whole body into six rectangles to fake this; it does not have to any more.
  splat: { art: 15 },
  parts0: { art: 16 },
  parts1: { art: 17 },
};

export const NAMES = Object.keys(POSE);
const INDEX = new Map(NAMES.map((n, i) => [n, i]));

/** Poses whose facing is part of the pose, which the renderer must never flip. */
export const FRONT_FRAMES = new Set(['idle0', 'idle1', 'idle2', 'idle3', 'idle4']);

/**
 * The run cycle: THREE frames, cells 5 to 7 of this sheet.
 *
 * It was three on an earlier sheet too, which appeared to offer five drawings of him
 * moving right. One of them -- art 4 there -- had both hands open and empty, with no
 * sword and no shield anywhere in the frame. In a cycle it read as him dropping his
 * weapon every fifth frame and picking it up again, which was exactly the complaint; it
 * was a good FALLING drawing and was used as one. Another, art 5 there, was a
 * front-facing stance with the blade raised: stepping through it while sprinting right
 * turned him to face the camera mid-stride. It was an idle drawing.
 *
 * What was left was three drawings in which he is side-on, moving, and gripping his
 * sword. Three is enough for a run at this speed; four would be better and needs a
 * fourth drawing, not a reused one.
 */
export const RUN_CYCLE = ['run0', 'run1', 'run2'];

/**
 * Standing still: the five-frame flourish, out and back.
 *
 *   centre - left - LEFT - left - centre - right - RIGHT - right - centre
 *
 * Nine steps at 0.9 Hz, so the loop runs ten seconds. Every entry is a DRAWING, and the
 * sword is in frame in all of them.
 *
 * Three earlier versions of this cycle are worth not repeating. Two tried to MANUFACTURE
 * a turn from a front drawing -- by narrowing the whole sprite, then by narrowing and
 * swinging the head -- and a turn is not a front view with something done to it. The
 * third used the only armed front drawing the old sheet had, which was its DEATH FRAME,
 * eyes crossed out and repaired in code. This sheet simply has the drawings.
 */
export const IDLE_CYCLE = [
  'idle0',
  'idle1', 'idle2', 'idle1',
  'idle0',
  'idle3', 'idle4', 'idle3',
  'idle0',
];

/**
 * Art the character is UNARMED in, and the only poses allowed to use it.
 *
 * Cell 14 is the death plunge -- screaming, crown flying off, everything dropped -- and
 * 16 and 17 are him already in pieces. Losing his sword and shield is the point of all
 * three, and of nothing else.
 *
 * He has twice lost his sword to a pose chosen for its shape without anyone checking
 * what was in his hands, so this is asserted rather than remembered.
 */
export const UNARMED_ART = new Set([14, 16, 17]);
// backfallHeld is cell 14 with his gear put BACK on him, so it is the one pose here that
// is armed again -- it reads from the unarmed cell and is allowed to.
export const UNARMED_OK = new Set(['backfall', 'backfallHeld', 'parts0', 'parts1']);

/** The pose the death plunge is drawn in, and the one the pieces burst out of. */
export const FALL_POSE = 'backfallHeld';

export const POSE_ART = Object.fromEntries(NAMES.map((n) => [n, POSE[n].art]));

export const DERIVED = NAMES.filter((n) => POSE[n].derived);

// --- baking --------------------------------------------------------------------

/**
 * One pose as a grid of colours (or null), ready to rasterise.
 *
 * `squash` compresses vertically and keeps the FEET on the bottom row, because the feet
 * are the edge the game positions him by. Squashing about the centre would float him.
 */
function poseGrid(name, facing) {
  const p = POSE[name];
  // Assembled rather than copied: see assembleHeld. Built once, facing right, and
  // MIRRORED for the left -- running the assembly again on a mirrored drawing would
  // round its pull direction the other way and give the two facings different bodies.
  if (p.hold) {
    const g = HELD.grid;
    return facing === 'left' ? g.map((r) => r.slice().reverse()) : g.map((r) => r.slice());
  }
  // `mirror` flips the DRAWING; `facing` flips the whole pose for movement. Work out
  // which it is up front, because the SOURCE has to change with it: a flipped pose reads
  // from the copy whose heraldry was mirrored in advance, so the flip cancels out.
  const flip = (facing === 'left') !== !!p.mirror;
  const src = ART[p.art];

  const out = Array.from({ length: SPR_H }, () => new Array(SPR_W).fill(null));
  const k = p.squash || 1;
  const destH = Math.max(1, Math.round(SPR_H * k));
  const top = SPR_H - destH;
  const bob = p.bob || 0;

  for (let y = 0; y < destH; y++) {
    const sy = Math.min(SPR_H - 1, Math.floor(y / k));
    const row = src[sy] || '';
    const dy = y + top + bob;
    if (dy < 0 || dy >= SPR_H) continue;
    for (let x = 0; x < SPR_W; x++) {
      const ch = row[x];
      if (!ch || ch === '.') continue;
      // A key with no colour is loud rather than invisible: an unmapped character is a
      // typo in generated data and should be impossible to miss.
      out[dy][flip ? SPR_W - 1 - x : x] = INKS[ch] || '#ff00ff';
    }
  }
  return out;
}

// --- colour by ROLE, never by palette letter -----------------------------------
//
// The palette is regenerated whenever the sheet is re-imported and its letters move
// with it: 'D' was a steel grey on one import and is a mid grey on this one. Anything
// that has to find "the gold" or "the blue" asks for a hue, the way gemsFor below
// already does, so a re-import cannot quietly turn his armour pink.
function tone(col) {
  const n = parseInt(col.slice(1), 16);
  const r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
  const mx = Math.max(r, g, b), mn = Math.min(r, g, b), d = mx - mn;
  let h = 0;
  if (d) {
    if (mx === r) h = 60 * (((g - b) / d) % 6);
    else if (mx === g) h = 60 * ((b - r) / d + 2);
    else h = 60 * ((r - g) / d + 4);
  }
  if (h < 0) h += 360;
  return { h, s: mx ? d / mx : 0, v: mx };
}
const ROLE_TEST = {
  // Gold: the crown, the cross, the rims. The same test the crown glint uses.
  gold: (c) => { const t = tone(c); return t.v >= 110 && t.s > 0.35 && t.h >= 28 && t.h <= 58; },
  // The tabard. Navy through azure.
  blue: (c) => { const t = tone(c); return t.s > 0.3 && t.h >= 200 && t.h <= 250 && t.v >= 50; },
  // The shield's field. His beard is the same family of reds, so a red has to be
  // saturated AND nearer crimson than auburn -- see "A shield found by its colour".
  red: (c) => { const t = tone(c); return t.s >= 0.5 && t.v >= 60 && (t.h <= 12 || t.h >= 345); },
  // Hair, beard and skin: the warm browns and tans that are not gold.
  warm: (c) => { const t = tone(c); return t.s >= 0.35 && t.h > 12 && t.h < 32 && t.v >= 70; },
  // Plate: unsaturated, neither the black outline nor the white specular.
  steel: (c) => { const t = tone(c); return t.s < 0.12 && t.v >= 70 && t.v <= 215; },
};
function shareOf(grid, cells, test) {
  let k = 0;
  for (const [x, y] of cells) if (test(grid[y][x])) k++;
  return cells.length ? k / cells.length : 0;
}

/** Every 8-connected piece of a drawing, biggest first, with its cells and box. */
function components(grid) {
  const seen = grid.map((r) => r.map(() => false));
  const out = [];
  for (let y = 0; y < SPR_H; y++) {
    for (let x = 0; x < SPR_W; x++) {
      if (!grid[y][x] || seen[y][x]) continue;
      const stack = [[x, y]];
      seen[y][x] = true;
      const cells = [];
      let x0 = x, y0 = y, x1 = x, y1 = y, sx = 0, sy = 0;
      while (stack.length) {
        const [cx, cy] = stack.pop();
        cells.push([cx, cy]);
        sx += cx; sy += cy;
        if (cx < x0) x0 = cx; if (cx > x1) x1 = cx;
        if (cy < y0) y0 = cy; if (cy > y1) y1 = cy;
        for (let dy = -1; dy <= 1; dy++) {
          for (let dx = -1; dx <= 1; dx++) {
            const nx = cx + dx, ny = cy + dy;
            if (nx < 0 || ny < 0 || nx >= SPR_W || ny >= SPR_H) continue;
            if (!grid[ny][nx] || seen[ny][nx]) continue;
            seen[ny][nx] = true;
            stack.push([nx, ny]);
          }
        }
      }
      out.push({ cells, n: cells.length, x0, y0, x1, y1,
        cx: sx / cells.length, cy: sy / cells.length });
    }
  }
  return out.sort((a, b) => b.n - a.n);
}

// Anything smaller than this is a stray resample pixel, not a piece of him. The same
// floor splitBits uses.
const MIN_PIECE = 24;
// How far a pulled-in piece is pushed INTO him past first contact: this fraction of its
// own narrower side, and never less than two art pixels. A fixed two pixels was tried
// first and read wrong at any angle but one -- a shield fifty pixels wide touching his
// sleeve at a single point hangs off him like a flag. A fifth of its width puts it
// against his forearm, which is what held means.
const HOLD_BITE = 0.18;
// The crown is walked further down, onto the head rather than the top of the hair: eight
// art pixels, about a fifth of its height. And where it lands on him, its DARK pixels give
// way to his -- the drawing shows the crown in the air from below, so its lower rows are
// the inside of the band, and painted over his hair that dark slot read as a gap between
// his head and his crown at every tumble but the upright one.
const CROWN_SEAT = 8;
const CROWN_DARK = 70;   // tone value (0-255) below which a crown pixel is its inside

/**
 * Put the plunge back together: cell 14 with everything that is flying off him moved
 * back onto him, plus where his parts are on that body.
 *
 * The drawing is a body and a handful of loose pieces -- a crown in the air above his
 * head, a shield and a sword falling away below. The body is the largest piece; each
 * loose one is walked toward it a pixel at a time until it touches, then HOLD_BITE of
 * its own width further, so it overlaps rather than abuts. The crown is walked straight DOWN, onto
 * the head it came off; everything else toward the body's centre, which lands the
 * shield on his forearm and the sword against his side. Strays under MIN_PIECE are left
 * where they were drawn.
 *
 * Found by shape and colour, never by coordinates, because the sheet is re-imported
 * and every coordinate in it moves when it is.
 *
 * The anchors are where each KIND of piece sits on this body, in its own art pixels --
 * so the splat can throw the head from where his head was and not from a clump in the
 * middle of him. See SPLAT_BITS.
 */
function assembleHeld(src) {
  const out = src.map((r) => r.slice());
  const comps = components(src);
  if (!comps.length) return { grid: out, anchors: {}, crown: null };
  const body = comps[0];
  const solid = new Uint8Array(SPR_W * SPR_H);
  for (const [x, y] of body.cells) solid[y * SPR_W + x] = 1;

  const loose = comps.slice(1).filter((c) => c.n >= MIN_PIECE);
  for (const c of loose) for (const [x, y] of c.cells) out[y][x] = null;

  // Which loose piece is which. The crown is the goldest; the shield the reddest.
  let crown = null, shield = null;
  for (const c of loose) {
    c.gold = shareOf(src, c.cells, ROLE_TEST.gold);
    c.red = shareOf(src, c.cells, ROLE_TEST.red);
    if (c.gold > 0.3 && (!crown || c.gold > crown.gold)) crown = c;
  }
  for (const c of loose) {
    if (c !== crown && c.red > 0.08 && (!shield || c.red > shield.red)) shield = c;
  }
  const sword = loose.find((c) => c !== crown && c !== shield) || null;

  const touches = (cells, dx, dy) => {
    for (const [x, y] of cells) {
      const px = x + dx, py = y + dy;
      for (let j = -1; j <= 1; j++) {
        for (let i = -1; i <= 1; i++) {
          const nx = px + i, ny = py + j;
          if (nx >= 0 && ny >= 0 && nx < SPR_W && ny < SPR_H && solid[ny * SPR_W + nx]) return true;
        }
      }
    }
    return false;
  };
  // Crown first, so the rest are pulled onto a body that is already wearing it.
  const order = [crown, ...loose.filter((c) => c !== crown)].filter(Boolean);
  for (const c of order) {
    let ux = 0, uy = 1;
    if (c !== crown) {
      const vx = body.cx - c.cx, vy = body.cy - c.cy;
      const len = Math.hypot(vx, vy) || 1;
      ux = vx / len; uy = vy / len;
    }
    let dx = 0, dy = 0;
    for (let t = 0; t < SPR_W + SPR_H; t++) {
      const tx = Math.round(ux * t), ty = Math.round(uy * t);
      if (touches(c.cells, tx, ty)) {
        const bite = Math.max(2, Math.round(HOLD_BITE * Math.min(c.x1 - c.x0 + 1, c.y1 - c.y0 + 1)));
        const k = t + (c === crown ? CROWN_SEAT : bite);
        dx = Math.round(ux * k); dy = Math.round(uy * k);
        break;
      }
    }
    c.dx = dx; c.dy = dy;
    for (const [x, y] of c.cells) {
      const nx = x + dx, ny = y + dy;
      if (nx < 0 || ny < 0 || nx >= SPR_W || ny >= SPR_H) continue;
      if (c === crown && solid[ny * SPR_W + nx] && tone(src[y][x]).v < CROWN_DARK) continue;
      out[ny][nx] = src[y][x];
      solid[ny * SPR_W + nx] = 1;
    }
  }

  // Back on the bottom row. Every pose stands on its cell's last row (test-sprites
  // fails any that does not), and pulling the sword up off it lifted the whole figure.
  let low = -1;
  for (let y = SPR_H - 1; y >= 0 && low < 0; y--) if (out[y].some(Boolean)) low = y;
  const shift = low < 0 ? 0 : SPR_H - 1 - low;
  const grid = shift
    ? out.map((_, y) => (y - shift >= 0 ? out[y - shift] : new Array(SPR_W).fill(null)))
    : out;

  // Where his parts are, in the assembled drawing's own pixels (y down).
  const at = (c) => (c ? { ax: c.cx + c.dx, ay: c.cy + c.dy + shift } : null);
  const bw = body.x1 - body.x0 + 1, bh = body.y1 - body.y0 + 1;
  let torso = { ax: body.cx, ay: body.cy + shift };
  {
    let n = 0, sx = 0, sy = 0;
    for (const [x, y] of body.cells) if (ROLE_TEST.blue(src[y][x])) { n++; sx += x; sy += y; }
    if (n > 20) torso = { ax: sx / n, ay: sy / n + shift };
  }
  let head = { ax: torso.ax, ay: torso.ay - bh * 0.3 };
  if (crown) {
    // The head is whatever of him is directly under the seated crown.
    const cx0 = crown.x0 + crown.dx, cx1 = crown.x1 + crown.dx;
    const top = crown.y1 + crown.dy + 1, bottom = top + (cx1 - cx0);
    let n = 0, sx = 0, sy = 0;
    for (const [x, y] of body.cells) {
      if (x >= cx0 && x <= cx1 && y >= top && y <= bottom) { n++; sx += x; sy += y; }
    }
    if (n > 20) head = { ax: sx / n, ay: sy / n + shift };
  }
  const anchors = {
    head,
    torso,
    crown: at(crown) || { ax: head.ax, ay: head.ay - bh * 0.15 },
    shield: at(shield) || { ax: torso.ax - bw * 0.3, ay: torso.ay },
    sword: at(sword) || { ax: torso.ax + bw * 0.3, ay: torso.ay },
    // Limbs are not separable in the plunge drawing, so they go where limbs go: arms
    // out to his sides a little above the tabard's centre, legs close in below it.
    arm: (k) => ({ ax: torso.ax + (k % 2 ? 1 : -1) * bw * (0.3 + 0.06 * (k >> 1)),
      ay: torso.ay - bh * (0.12 - 0.08 * (k >> 1)) }),
    leg: (k) => ({ ax: torso.ax + (k % 2 ? 1 : -1) * bw * 0.1, ay: torso.ay + bh * 0.3 }),
  };
  return { grid, anchors, crown: crown ? { ...crown, dy: crown.dy + shift } : null, src };
}

// Built once, before FRAMES, because poseGrid reads it for the held pose.
const HELD = assembleHeld(poseGrid('backfall', 'right'));

/** Every pose in both facings, built once at load. Both are exported so the test suite
 *  can check them against each other rather than against a private copy. */
export const FRAMES = Object.fromEntries(NAMES.map((n) => [n, poseGrid(n, 'right')]));
export const FRAMES_LEFT = Object.fromEntries(NAMES.map((n) => [n, poseGrid(n, 'left')]));

/**
 * The last row of a pose that goes into the drawing atlas: for a pose he STANDS in, the
 * row his boots end on, and nothing under it.
 *
 * Once his boots were put on the landing line (bootDrop), what the drop left under the
 * line was the point of his heater shield, held low beside him in every idle -- two or
 * three art rows and the black shadow under them, drawn IN FRONT of the ledge's lit top
 * rows, since he is drawn after the ledges. On a flat deck (DOWNTOWN's gallery, STORM's
 * cloud, the ground) the V of the shield notched the one line a player tracks, right
 * beside his feet. Left out of the atlas, the point ends on the deck, as if resting on it
 * behind the ledge's front edge.
 *
 * Cut here rather than by a clip or a shorter source rect in drawSprite, so the draw call
 * is the one it was: at the zooms between 2 and 1 a changed rect or box moves which art
 * row a screen pixel samples, all the way up his body. This way every pixel above the
 * line is exactly what it was, and under it the rows are simply empty.
 *
 * Only the standing poses, which drawSprite draws only standing, boots on the line: the
 * strides and the landing end on their bottom row and lose nothing; airborne, dying and
 * scene poses keep every row, and FRAMES, the grids tools and tests read, keep the point.
 */
function atlasRows(name) {
  return GROUND_POSES.has(name) ? SPR_H - Math.round((FOOT_DROP[name] || 0) * PX) : SPR_H;
}

function rasterise(grids) {
  const { c, g } = newCanvas(NAMES.length * SPR_W, SPR_H);
  NAMES.forEach((name, i) => {
    const buf = grids[name];
    const rows = atlasRows(name);
    for (let y = 0; y < rows; y++) {
      let x = 0;
      while (x < SPR_W) {
        const col = buf[y][x];
        if (!col) { x++; continue; }
        let run = 1;
        while (x + run < SPR_W && buf[y][x + run] === col) run++;
        g.fillStyle = col;
        g.fillRect(i * SPR_W + x, y, run, 1);
        x += run;
      }
    }
  });
  return c;
}

let atlas = null, atlasFlip = null;

export function spriteAtlas(flip) {
  if (flip) { if (!atlasFlip) atlasFlip = rasterise(FRAMES_LEFT); return atlasFlip; }
  if (!atlas) atlas = rasterise(FRAMES);
  return atlas;
}

/**
 * How far each pose must be LOWERED so it stands on its feet rather than on whatever
 * happens to be its lowest pixel.
 *
 * Every pose is positioned by the bottom of its cell, and the importer bottom-aligns
 * each frame on its own lowest ink. For a standing pose that is the boots and it is
 * right. For a running pose it is the TIP OF HIS SWORD, which in this sheet points down
 * and back past his heel -- so the sprite hung from the sword tip and his boots floated.
 * Measured: run1 and fall hovered 1.25 world units, ten screen pixels at the closest
 * zoom. That is the float the user reported, the Duke still off the ground.
 *
 * A foot row is the lowest row with a real FOOTPRINT rather than a dangling point. The
 * ink tapers smoothly down a blade, so there is no sharp edge to find; eight pixels --
 * about 6.5% of the sprite's width -- is the line between a boot and a sword tip, and it
 * is checked by eye with tools/shot-stand.mjs rather than asserted on faith.
 *
 * Anything below the foot row still draws. A sword tip now overlaps the platform edge,
 * which is what a sword hanging past your heel does.
 *
 * That was one sheet ago. The poses he STANDS in are anchored on their boots now, by
 * bootDrop below, because on this sheet FOOT_INK stands him on his shield; the rest --
 * in the air, or lying in a heap -- still use it.
 */
const FOOT_INK = 8;

/**
 * The largest connected piece of a drawing: HIM, rather than what is lying beside him.
 *
 * Some cells are a scene. The knockout is a body, a dropped shield and a fallen crown,
 * drawn at three different depths, so their lowest pixels are eighteen art pixels apart.
 * Anchoring on the whole cell anchored on the SHIELD, whose point dips lowest, and left
 * his body four and a half world units in the air -- lying flat, on nothing.
 *
 * For every ordinary pose the largest piece is him with his sword and shield in it, so
 * this changes nothing there and FOOT_INK still keeps the anchor off the blade.
 */
function largestPiece(grid) {
  const seen = grid.map((r) => r.map(() => false));
  let best = null, bestN = 0;
  for (let y = 0; y < SPR_H; y++) {
    for (let x = 0; x < SPR_W; x++) {
      if (!grid[y][x] || seen[y][x]) continue;
      const stack = [[x, y]];
      seen[y][x] = true;
      const cells = [];
      while (stack.length) {
        const [cx, cy] = stack.pop();
        cells.push([cx, cy]);
        for (let dy = -1; dy <= 1; dy++) {
          for (let dx = -1; dx <= 1; dx++) {
            const nx = cx + dx, ny = cy + dy;
            if (nx < 0 || ny < 0 || nx >= SPR_W || ny >= SPR_H) continue;
            if (!grid[ny][nx] || seen[ny][nx]) continue;
            seen[ny][nx] = true;
            stack.push([nx, ny]);
          }
        }
      }
      if (cells.length > bestN) { bestN = cells.length; best = cells; }
    }
  }
  return best || [];
}

/**
 * Poses that are a SCENE on the ground rather than a figure: him already down, with his
 * gear scattered around him.
 *
 * Only these measure their anchor from the largest piece. Every other pose measures the
 * whole cell, and must: the death plunge also has loose gear in it, but he is in the AIR
 * there, so re-anchoring on his body alone would drop him ten world units the instant the
 * pose changes. There is no ground under a falling man to put him on.
 */
const SCENE_POSES = new Set(['dazed', 'splat']);

function footDrop(grid, scene) {
  const ink = new Int32Array(SPR_H);
  if (scene) {
    // Counted over the largest piece only, so a dropped shield cannot decide where he
    // lies. His body bottoms out eighteen art pixels above the shield's point, and
    // anchoring on the cell left him lying flat four and a half world units in the air.
    for (const [, y] of largestPiece(grid)) ink[y]++;
  } else {
    for (let y = 0; y < SPR_H; y++) {
      for (let x = 0; x < SPR_W; x++) if (grid[y][x]) ink[y]++;
    }
  }
  for (let y = SPR_H - 1; y >= 0; y--) {
    if (ink[y] >= FOOT_INK) return (SPR_H - 1 - y) / PX;
  }
  return 0;
}

/**
 * The poses drawn STANDING ON A LEDGE: every pose frameFor picks while he is grounded,
 * and the run the title screen puts on its bar. These are anchored on their BOOTS.
 *
 * FOOT_INK was right for the sheet it was measured on and wrong for every sheet since.
 * Three imports later nothing hangs past his heel, and what reaches the bottom of the
 * standing cells is the POINT OF HIS SHIELD: he holds the heater low beside him, and it
 * is as blunt as a boot at the bottom -- nine pixels on its last row in idle0, so FOOT_INK
 * took it for a footprint and stood him on it. In the other four idles it skipped the
 * point's last row, one to six pixels wide, and stood him on its second. Either way the
 * boots hung one or two art pixels over the ledge, up to half a world unit, and the idle
 * is where he stands still: two screen pixels of sky under his soles at zoom 1, four at
 * zoom 2, on every ledge. The grass on the old ledges hid it; a flat timber deck did not.
 * And the same threshold cut the other way on the run: run1's and run2's toes end in a
 * six- and a four-pixel row, which it skipped, so the toe sank a pixel into the ledge.
 *
 * So these ask what the lowest pixel IS rather than how wide it is. Airborne poses keep
 * FOOT_INK -- there is no ledge under him to measure against, the fall's anchor is where
 * the splat throws his pieces from (posePoint), and nothing about them was reported.
 */
const GROUND_POSES = new Set([...IDLE_CYCLE, ...RUN_CYCLE, 'land']);

// A pixel under this brightness (tone value, 0-255) is outline or cast shadow. Both the
// shield and the boots are ringed in near-black, and the shield's point sits on a black
// shadow of its own, so a dark pixel says nothing about which one it belongs to.
const FOOT_LIT = 70;
// How far up a column (art pixels) the colours get a vote. Far enough to get past a
// boot's sole -- up to four rows of black under a toe -- and into the plate above it.
const FOOT_REACH = 10;

/**
 * How far a GROUNDED pose must be lowered to stand on its boots: the lowest row of ink
 * that is not the shield.
 *
 * Found by colour, per column of the drawing's bottom edge. The lit pixels in the few
 * rows above a column's lowest ink vote: the shield's rim and field are GOLD and CRIMSON,
 * his sabatons are STEEL, and the browns both share abstain. A column dark all the way
 * up -- the shadow under the shield's point, a thick sole -- goes with the nearest
 * column it is joined to along the bottom that did get a verdict. The boots' lowest row
 * then sits on the ledge. The shield's point below it used to hang over the ledge's lip
 * in front of it, across the ledge's lit top rows; the atlas now leaves out a standing
 * pose's rows under its boots (atlasRows), so the point ends on the deck.
 *
 * Measured on this sheet by eye, before this was written, and it agrees on all nine:
 * boots end on row 209 in idle0 and idle2, 208 in idle1, idle3 and idle4, and on the last
 * row, 211, in the three strides and the landing -- where a toe is the lowest thing.
 * test-sprites holds the rule to those rows, so a re-import that moves his feet fails
 * there and gets looked at, instead of drifting the way FOOT_INK did.
 *
 * It would take a blade hanging below the heel for a boot, as the sheet before this one
 * had: steel is steel. Should that come back, the test fails first.
 */
function bootDrop(grid) {
  const low = new Int32Array(SPR_W).fill(-1);
  const vote = new Int8Array(SPR_W);        // +1 boot, -1 shield, 0 no verdict
  for (let x = 0; x < SPR_W; x++) {
    let y = SPR_H - 1;
    while (y >= 0 && !grid[y][x]) y--;
    if (y < 0) continue;
    low[x] = y;
    let steel = 0, arms = 0;
    for (let yy = y; yy >= Math.max(0, y - FOOT_REACH); yy--) {
      const c = grid[yy][x];
      if (!c || tone(c).v < FOOT_LIT) continue;
      if (ROLE_TEST.gold(c) || ROLE_TEST.red(c)) arms++;
      else if (ROLE_TEST.steel(c)) steel++;
    }
    vote[x] = Math.sign(steel - arms);
  }
  // The undecided take the nearest verdict they are joined to: walk out both ways across
  // columns that all have ink, and stop at the first gap in the silhouette. A piece with
  // no verdict anywhere in it -- a detached fleck of shadow -- decides nothing.
  const side = (x, dir) => {
    for (let d = 1, xx = x + dir; xx >= 0 && xx < SPR_W && low[xx] >= 0; d++, xx += dir) {
      if (vote[xx]) return { d, v: vote[xx] };
    }
    return null;
  };
  let row = -1;
  for (let x = 0; x < SPR_W; x++) {
    if (low[x] < 0) continue;
    let v = vote[x];
    if (!v) {
      const l = side(x, -1), r = side(x, 1);
      v = !l ? (r ? r.v : 0) : !r ? l.v : (l.d <= r.d ? l.v : r.v);
    }
    if (v > 0 && low[x] > row) row = low[x];
  }
  return row < 0 ? footDrop(grid, false) : (SPR_H - 1 - row) / PX;
}

export const FOOT_DROP = Object.fromEntries(NAMES.map((n) => [n,
  GROUND_POSES.has(n) ? bootDrop(FRAMES[n]) : footDrop(FRAMES[n], SCENE_POSES.has(n))]));

/**
 * The individual BITS he comes apart into, found in the two `parts` drawings.
 *
 * Those two cells are a parts bin, not a pose: a torso, a head, arms, legs, his sword
 * and his shield, arranged to fit the cell rather than to stand in it. Drawn whole and
 * bottom-aligned like any other frame, the arms end up seventy pixels in the air.
 *
 * So each connected piece is found and exposed on its own, and the renderer scatters
 * them along the floor. Ordered biggest first, so the torso lands before the fingers
 * and the small pieces settle on top.
 *
 * Each bit keeps its own CELLS, not just its box. The torso's box and the arm drawn
 * hanging beside it overlap by eleven columns, and a bit copied out of its box used to
 * carry a slice of its neighbour with it.
 */
function splitBits(name) {
  const grid = FRAMES[name];
  if (!grid) return [];
  return components(grid)
    .filter((c) => c.n >= MIN_PIECE)
    .map((c) => ({ frame: name, grid, cells: c.cells, n: c.n,
      sx: c.x0, sy: c.y0, sw: c.x1 - c.x0 + 1, sh: c.y1 - c.y0 + 1 }));
}

/**
 * What each bit IS, so it can start the burst where that part of him was.
 *
 * The two bins are laid out as the upper body and the lower: a head, a torso and arms
 * in one, legs, the sword and the shield in the other. Inside a bin the roles are told
 * apart by colour -- the tabard is the bluest thing he wears, his hair and beard the
 * warmest, the shield's field the reddest -- and the sword is the sparsest piece, a thin
 * blade in a big box. Asked by hue and by rank, never by coordinate or palette letter,
 * so a re-import that moves every piece still sorts them.
 */
function assignRoles(bits) {
  // A plate cut off the torso (cutLimbs) is what it was cut as: asked by colour it would
  // rank as an arm, and take an arm's slot at the burst.
  const upper = bits.filter((b) => b.frame === 'parts0' && b.role !== 'plate');
  const lower = bits.filter((b) => b.frame === 'parts1' && b.role !== 'plate');
  const best = (list, score) => list.reduce((a, b) => (!a || score(b) > score(a) ? b : a), null);
  const share = (b, test) => shareOf(b.grid, b.cells, test);
  const torso = best(upper, (b) => share(b, ROLE_TEST.blue));
  const head = best(upper.filter((b) => b !== torso), (b) => share(b, ROLE_TEST.warm));
  const shield = best(lower, (b) => share(b, ROLE_TEST.red));
  const sword = best(lower.filter((b) => b !== shield), (b) => -b.n / (b.sw * b.sh));
  for (const b of upper) b.role = b === torso ? 'torso' : b === head ? 'head' : 'arm';
  for (const b of lower) b.role = b === shield ? 'shield' : b === sword ? 'sword' : 'leg';
  return bits;
}

/**
 * An arm the artist left ON the torso, cut off it.
 *
 * The parts bin is meant to hold one piece per part, and on this import it does not:
 * three arms are drawn loose, and the fourth -- pauldron, vambrace and gauntlet -- hangs
 * from the torso's shoulder, touching the tabard all down its armhole. Being one
 * connected piece, it flew as the torso: a tabard with an arm dangling off it while the
 * other three arms flew free. The import before drew it loose (eleven pieces, then ten).
 *
 * The cut is read from the drawing, never from a coordinate, so a re-import still works:
 *  - the torso is its TABARD, the biggest patch of blue in the piece;
 *  - what hangs off it is measured by how far each pixel is from the tabard, walking
 *    inside the piece;
 *  - the cut is the cheapest line of pixels separating the tabard from the far end of
 *    what hangs off it, where outline ink costs 1 and lit ink up to 9 (a minimum vertex
 *    cut, cutAt). Two drawn parts meet along an outline, so that is where it runs: here
 *    down the tabard's armhole, 41 pixels, every one of them outline;
 *  - and it is an ARM only if it takes as much ink as the arms he drew loose
 *    (LIMB_MATCH). Where the far end is taken to start decides where the cheapest line
 *    lies -- from the gauntlet alone it is the wrist, from the forearm the elbow -- so the
 *    far end is tried from 30% of the way out to 90%, and the cut kept is the one whose
 *    piece is nearest an arm. Here that is the whole arm, pauldron and all: 1579 px
 *    against loose arms of 1503-1545 (the median, 1511, is the measure), where starting
 *    the far end at 60% cuts at the elbow and takes 853.
 *
 * The cut line goes to BOTH pieces: it is the outline each of them has where the other
 * one was, as the art's own pieces have one all round. A pixel of it that is not outline
 * ink (none on this sheet) is painted in the piece's commonest outline colour. Then it
 * looks again for a second arm, until what it would cut off is not an arm: the torso's
 * own right pauldron, the farthest thing left on it (378 px, -75%). That comes off last, as
 * a PLATE: the cut is kept if it takes at least PLATE_MIN of an arm and is mostly steel
 * (PLATE_STEEL), so the tabard does not lie wearing a steel shoulder.
 *
 * Each piece cut off keeps where it HUNG (`hang`): its box's centre from the torso's, in art
 * pixels. The burst starts it there, beside wherever the torso starts, so at the instant
 * he comes apart the two are the drawing they were cut from and the arm comes off the
 * shoulder it was drawn on -- rather than from a slot for loose arms, which is somewhere
 * else on him.
 */
function cutLimbs(bits) {
  const torso = bits.find((b) => b.role === 'torso');
  const arms = bits.filter((b) => b.role === 'arm').map((b) => b.n).sort((a, b) => a - b);
  // No loose arm, no measure of one: nothing is cut rather than something guessed at.
  if (!torso || !arms.length) return bits;
  const ref = arms[arms.length >> 1];
  const out = bits.filter((b) => b !== torso);
  const limbs = [];
  let body = torso;
  for (let k = 0; k < 4; k++) {
    const cut = cutLimb(body, ref);
    if (!cut) break;
    limbs.push(cut.limb);
    body = cut.body;
  }
  // Then the torso's own right pauldron. The loop above stops at the first cut too small to
  // be an arm, and that was it: a plate of steel on the torso's shoulder, 378 px, a quarter
  // of an arm. Left on, it flew and lay as a stump -- the user, of the build with the fused
  // arm already cut free, still saw an arm that did not come off properly at the death, and in
  // the settled pieces the tabard still wore a steel shoulder. It comes off as a piece of its
  // own now (PLATE_MIN, cutLimb's 'plate' mode), and starts where it hung, like a cut arm.
  const plate = cutLimb(body, ref, 'plate');
  if (plate) { limbs.push(plate.limb); body = plate.body; }
  // From the torso as it is finally drawn, after every cut: that is the box the burst
  // centres on the torso's anchor.
  for (const limb of limbs) {
    limb.hang = { dx: limb.sx + limb.sw / 2 - (body.sx + body.sw / 2),
      dy: limb.sy + limb.sh / 2 - (body.sy + body.sh / 2) };
  }
  return out.concat(limbs, [body]);
}

// The far end of what hangs off the tabard is tried from this share of the way out.
const LIMB_SEEDS = [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9];

/**
 * One arm cut off `piece`, or null if nothing hanging off its tabard is arm-sized. In 'plate'
 * mode, the plate of armour left hanging off it instead: smaller than an arm (under
 * 1 - LIMB_MATCH of one) but at least PLATE_MIN of one, and at least PLATE_STEEL steel.
 */
function cutLimb(piece, ref, mode = 'arm') {
  const W = SPR_W, grid = piece.grid, cells = piece.cells, n = cells.length;
  const at = new Int32Array(SPR_W * SPR_H).fill(-1);
  const px = new Int32Array(n), py = new Int32Array(n);
  cells.forEach(([x, y], k) => { at[y * W + x] = k; px[k] = x; py[k] = y; });
  // Each pixel's 8 neighbours inside the piece, as one flat list: pixel k's are
  // nbList[nbAt[k] .. nbAt[k + 1]). Flat, because the flow below walks them thousands of
  // times and an array per pixel was most of what it cost to load.
  const nbAt = new Int32Array(n + 1), nbList = new Int32Array(8 * n);
  for (let k = 0, m = 0; k < n; k++) {
    nbAt[k] = m;
    for (let dy = -1; dy <= 1; dy++) {
      for (let dx = -1; dx <= 1; dx++) {
        const nx = px[k] + dx, ny = py[k] + dy;
        if ((dx || dy) && nx >= 0 && ny >= 0 && nx < SPR_W && ny < SPR_H && at[ny * W + nx] >= 0) nbList[m++] = at[ny * W + nx];
      }
    }
    nbAt[k + 1] = m;
  }
  // The palette is a few dozen colours: read each one's tone once.
  const vOf = new Map();
  const value = (c) => { let v = vOf.get(c); if (v === undefined) vOf.set(c, v = tone(c).v); return v; };

  // The tabard: the largest 4-connected patch of blue. 4-connected, because the steel
  // has blue glints in it that touch the tabard only at a corner.
  const blue = cells.map(([x, y]) => ROLE_TEST.blue(grid[y][x]));
  let tabard = [];
  {
    const seen = new Uint8Array(n);
    for (let s = 0; s < n; s++) {
      if (!blue[s] || seen[s]) continue;
      const patch = [s];
      seen[s] = 1;
      for (let h = 0; h < patch.length; h++) {
        const k = patch[h];
        for (let m = nbAt[k]; m < nbAt[k + 1]; m++) {
          const j = nbList[m];
          if (blue[j] && !seen[j] && (px[j] === px[k] || py[j] === py[k])) { seen[j] = 1; patch.push(j); }
        }
      }
      if (patch.length > tabard.length) tabard = patch;
    }
  }
  if (tabard.length < MIN_PIECE) return null;

  // How far out from the tabard each pixel is, walking inside the piece.
  const reach = new Int32Array(n).fill(-1);
  const queue = tabard.slice();
  for (const k of queue) reach[k] = 0;
  for (let h = 0; h < queue.length; h++) {
    const k = queue[h];
    for (let m = nbAt[k]; m < nbAt[k + 1]; m++) {
      const j = nbList[m];
      if (reach[j] < 0) { reach[j] = reach[k] + 1; queue.push(j); }
    }
  }
  let far = 0, tip = -1;
  for (let k = 0; k < n; k++) if (reach[k] > far) { far = reach[k]; tip = k; }
  if (!far) return null;

  const cost = cells.map(([x, y]) => {
    const v = value(grid[y][x]);
    return v < CUT_OUTLINE_V ? 1 : 1 + Math.round(v / 32);
  });
  const cutAt = minCut(n, nbAt, nbList, cost, tabard);
  let best = null;
  for (const share of LIMB_SEEDS) {
    // The far end is the pixels at least `share` of the way out that are joined to the
    // farthest one through pixels as far out: the end of ONE thing hanging off the tabard.
    // It was every pixel that far out, and at 30% and 40% that took in ends of the torso's
    // own right side as well (flecks of 54 and 6 px, then 4), so the cut went round them
    // too and they would have flown off with the arm as specks of their own. On this sheet
    // 50% won by 0.3% of an arm (1579 px against 1583, fleck and all); with the armhole
    // painted over in lit steel, 40% won and the fleck flew. Now 30-50% all make the same
    // clean cut.
    const sink = [tip];
    const inSink = new Uint8Array(n);
    inSink[tip] = 1;
    for (let h = 0; h < sink.length; h++) {
      const k = sink[h];
      for (let m = nbAt[k]; m < nbAt[k + 1]; m++) {
        const j = nbList[m];
        if (!inSink[j] && reach[j] >= share * far) { inSink[j] = 1; sink.push(j); }
      }
    }
    const line = cutAt(sink);
    if (!line) continue;
    // Which side of the line each pixel is on: joined to the tabard without crossing it,
    // or not.
    const side = new Uint8Array(n);           // 0 limb, 1 body, 2 the line itself
    for (const k of line) side[k] = 2;
    const walk = tabard.filter((k) => side[k] !== 2);
    for (const k of walk) side[k] = 1;
    for (let h = 0; h < walk.length; h++) {
      const k = walk[h];
      for (let m = nbAt[k]; m < nbAt[k + 1]; m++) if (!side[nbList[m]]) { side[nbList[m]] = 1; walk.push(nbList[m]); }
    }
    let limbInk = line.length;
    for (let k = 0; k < n; k++) if (!side[k]) limbInk++;
    const size = limbInk / ref;
    if (mode === 'arm') {
      const miss = Math.abs(size - 1);
      if (miss <= LIMB_MATCH && (!best || miss < best.miss)) best = { miss, side };
      // A far end that starts further out lies inside the last one, and so does its cut:
      // once a cut takes too little to be an arm, every later one does too.
      if (limbInk < ref * (1 - LIMB_MATCH)) break;
    } else {
      // The whole plate, not a sliver of it: of the cuts in range, the one that takes most.
      if (size < PLATE_MIN) break;
      if (size < 1 - LIMB_MATCH) {
        let lit = 0, steel = 0;
        for (let k = 0; k < n; k++) {
          if (side[k]) continue;
          const c = grid[py[k]][px[k]];
          if (value(c) < CUT_OUTLINE_V) continue;
          lit++;
          if (ROLE_TEST.steel(c)) steel++;
        }
        if (lit && steel / lit >= PLATE_STEEL && (!best || size > best.size)) best = { size, side };
      }
    }
  }
  if (!best) return null;

  // The line belongs to both. Where it runs through lit ink rather than an outline,
  // both pieces get the piece's commonest outline colour there instead.
  const tally = {};
  for (const [x, y] of cells) {
    const c = grid[y][x];
    if (value(c) < CUT_OUTLINE_V) tally[c] = (tally[c] || 0) + 1;
  }
  const ink = Object.keys(tally).sort((a, b) => tally[b] - tally[a])[0] || '#000000';
  const g2 = grid.map((r) => r.slice());
  const make = (keep, role) => {
    const own = [];
    let x0 = SPR_W, y0 = SPR_H, x1 = -1, y1 = -1;
    cells.forEach(([x, y], k) => {
      if (!keep(best.side[k])) return;
      own.push([x, y]);
      if (best.side[k] === 2 && value(grid[y][x]) >= CUT_OUTLINE_V) g2[y][x] = ink;
      if (x < x0) x0 = x; if (x > x1) x1 = x;
      if (y < y0) y0 = y; if (y > y1) y1 = y;
    });
    return { frame: piece.frame, grid: g2, cells: own, n: own.length, role,
      sx: x0, sy: y0, sw: x1 - x0 + 1, sh: y1 - y0 + 1 };
  };
  return { body: make((s) => s >= 1, piece.role), limb: make((s) => s !== 1, mode) };
}

/**
 * The cheapest set of pixels whose removal separates `source` from a sink set, as a
 * function of the sink set -- the graph is built once and reused for every sink tried.
 * Each pixel is a node split in two, joined by an edge of its cost; neighbours are
 * joined both ways without limit; the maximum flow's saturated pixel edges are the cut.
 *
 * Dinic's method: one breadth-first pass lays out the level graph, then as many paths as
 * it holds are pushed before the next. One shortest path per pass, which was the first
 * version, was 72 ms of BFS at every load of the game for the forty or so units of flow a
 * cut here carries.
 */
function minCut(n, nbAt, nbList, cost, source) {
  const S = 2 * n, T = 2 * n + 1, N = 2 * n + 2, INF = 1 << 28;
  // in -> out and out -> T for every pixel, out -> in for every neighbour, S -> in for the source
  const edges = 2 * n + nbAt[n] + source.length;
  const to = new Int32Array(2 * edges), next = new Int32Array(2 * edges);
  const base = new Int32Array(2 * edges), head = new Int32Array(N).fill(-1);
  let e = 0;
  const add = (u, v, c) => {
    to[e] = v; base[e] = c; next[e] = head[u]; head[u] = e++;
    to[e] = u; base[e] = 0; next[e] = head[v]; head[v] = e++;
  };
  const isSource = new Uint8Array(n);
  for (const k of source) isSource[k] = 1;
  const pixel = new Int32Array(n), toSink = new Int32Array(n);
  for (let k = 0; k < n; k++) {
    pixel[k] = e;
    add(2 * k, 2 * k + 1, isSource[k] ? INF : cost[k]);
    for (let m = nbAt[k]; m < nbAt[k + 1]; m++) add(2 * k + 1, 2 * nbList[m], INF);
    toSink[k] = e;
    add(2 * k + 1, T, 0);
  }
  for (const k of source) add(S, 2 * k, INF);
  const cap = new Int32Array(2 * edges), level = new Int32Array(N), it = new Int32Array(N);
  const q = new Int32Array(N);
  const layer = () => {
    level.fill(-1);
    level[S] = 0;
    let qh = 0, qt = 0;
    q[qt++] = S;
    while (qh < qt) {
      const u = q[qh++];
      for (let i = head[u]; i >= 0; i = next[i]) {
        if (cap[i] > 0 && level[to[i]] < 0) { level[to[i]] = level[u] + 1; q[qt++] = to[i]; }
      }
    }
    return level[T] >= 0;
  };
  // Paths are a shortest route across a piece, a hundred or so nodes: recursion is fine.
  const push = (u, f) => {
    if (u === T) return f;
    for (; it[u] >= 0; it[u] = next[it[u]]) {
      const i = it[u], v = to[i];
      if (cap[i] > 0 && level[v] === level[u] + 1) {
        const d = push(v, Math.min(f, cap[i]));
        if (d > 0) { cap[i] -= d; cap[i ^ 1] += d; return d; }
      }
    }
    return 0;
  };
  return (sink) => {
    cap.set(base);
    for (const k of sink) {
      if (isSource[k]) return null;
      cap[pixel[k]] = INF;
      cap[toSink[k]] = INF;
    }
    while (layer()) {
      it.set(head);
      for (let f = push(S, INF); f > 0; f = push(S, INF)) {
        if (f >= INF) return null;         // the sink touches the tabard: no cut exists
      }
    }
    // The cut: pixels whose in-half the source still reaches and whose out-half it does
    // not. The last layer() found no path, so `level` marks exactly what it reaches.
    const line = [];
    for (let k = 0; k < n; k++) if (level[2 * k] >= 0 && level[2 * k + 1] < 0) line.push(k);
    return line;
  };
}

/** The crown, cut out of the plunge drawing: in the fall it is on his head, so it has
 *  to come off him at the bottom like everything else. */
function crownBit() {
  const c = HELD.crown;
  if (!c) return [];
  return [{ frame: 'backfall', grid: HELD.src, cells: c.cells, n: c.n, role: 'crown',
    sx: c.x0, sy: c.y0, sw: c.x1 - c.x0 + 1, sh: c.y1 - c.y0 + 1 }];
}

/**
 * Each bit on its OWN small canvas, rather than as a rectangle of the shared atlas.
 *
 * The obvious way is a sub-rectangle of the shared atlas, and it does not work. The
 * atlas is one SPR_W cell per pose -- twenty poses of 252 now, so the parts frames sit
 * at source x 4536 and 4788 (1768 and 1872 on the nineteen-pose, 104-wide atlas where
 * this was found) -- and the headless canvas's drawImage silently draws NOTHING from a
 * source offset that large: the pieces were absent from every test render while
 * getImageData at the same coordinates returned them perfectly. Real Chromium is very
 * probably fine, but "very
 * probably" is not a thing to ship a death animation on, and a tool that cannot show me
 * the frame is worse than useless: it is misleading.
 *
 * One canvas per piece removes the offset entirely, and it is the call shape the
 * companions already use, which is known to work everywhere.
 *
 * The canvases are built by warmSplat(), which the Renderer calls at construction, not
 * at module load. The SIMULATION reads this list too -- a piece's size decides where
 * it rests and how it bounces -- and the headless bot suites load the game with no
 * canvas in existence at all.
 *
 * Every bit carries, for the game:
 *   w, h     its size in world units, unrotated
 *   role     head, torso, arm, leg, shield, sword or crown (see assignRoles)
 *   anchor   { ax, ay }: where that part of him is on the FALL_POSE drawing, in its art
 *            pixels, y down. posePoint() turns it into a world position.
 *   hang     only on a piece cut off the torso: { dx, dy } from the torso's box centre to
 *            its own in the parts drawing, art pixels; an arm's anchor is the torso's plus this.
 *
 * Roles are asked twice: once to find the torso and the loose arms that cutLimbs measures
 * by, and again once it has cut, because what it cut off is only arm-SIZED. A head drawn
 * touching the collar comes off the same way (tried: bridge this sheet's three-pixel neck
 * gap and it is cut at the neck, 1735 px) and is the head by colour, like any other; asked
 * once, it flew as an arm and a loose arm, the next-warmest piece, was taken for the head.
 */
export const PARTS_BITS = assignRoles(cutLimbs(assignRoles(['parts0', 'parts1'].flatMap(splitBits))))
  .concat(crownBit())
  .sort((a, b) => b.n - a.n)
  .map((bit) => ({ ...bit, w: bit.sw / PX, h: bit.sh / PX }));

/**
 * The share of two pieces' silhouettes that coincide when `b` is mirrored left to right, each
 * laid on its own centroid [0..1]: how nearly they are a left and a right of one thing.
 */
function mirrorShare(a, b) {
  const at = (p, flip) => {
    let sx = 0, sy = 0;
    for (const [x, y] of p.cells) { sx += x; sy += y; }
    const cx = sx / p.cells.length, cy = sy / p.cells.length;
    return new Set(p.cells.map(([x, y]) => `${Math.round(flip ? cx - x : x - cx)},${Math.round(y - cy)}`));
  };
  const A = at(a, false), B = at(b, true);
  let both = 0;
  for (const k of A) if (B.has(k)) both++;
  return both / (A.size + B.size - both);
}

/**
 * What he comes apart into: ONE body's worth of those pieces.
 *
 * The parts drawing has four arms -- three near-copies of one arm (their silhouettes overlap
 * 0.79 to 0.85) and one of the other side, the arm cut off the torso -- and the burst threw all
 * four, with a fifth steel shoulder beside them, the plate cut off the tabard: the user saw four
 * arms fly out at a death (2026-09-29). Kept: the two arms most nearly each other's mirror
 * image, a left and a right (on this sheet the cut arm and a loose one, 0.74 of their silhouettes
 * shared with one flipped, against 0.53 to 0.60 for the other two), and no plate: each arm wears
 * its own pauldron. PARTS_BITS keeps every piece the drawing was cut into, for the tests that
 * hold the cutting.
 */
function oneBody(bits) {
  const arms = bits.filter((b) => b.role === 'arm');
  let keep = arms;
  if (arms.length > 2) {
    let best = -1;
    for (let i = 0; i < arms.length; i++) {
      for (let j = i + 1; j < arms.length; j++) {
        const s = mirrorShare(arms[i], arms[j]);
        if (s > best) { best = s; keep = [arms[i], arms[j]]; }
      }
    }
  }
  return bits.filter((b) => b.role !== 'plate' && (b.role !== 'arm' || keep.includes(b)));
}

export const SPLAT_BITS = oneBody(PARTS_BITS);
{
  const a = HELD.anchors;
  // Loose limbs take the slots at his sides in size order (anchors.arm: even slots on his
  // left, odd on his right). An arm cut off the torso starts where it hung off it instead
  // (see cutLimbs) and holds the slot on its own side, so the loose arms fill the others:
  // two arms a side at the burst. Handed out in plain size order, as they were before
  // anything was cut, that made three on the side it hung on and one on the other. A head
  // cut off the torso has a real place on the fall pose, under the crown, and goes there.
  const cutArm = (b) => b.hang && b.role === 'arm';
  // Anything cut off the torso -- an arm, or the pauldron -- starts where it hung.
  const cutOff = (b) => !!b.hang;
  const held = new Set();
  for (const b of SPLAT_BITS) {
    if (!cutArm(b)) continue;
    let k = b.hang.dx < 0 ? 0 : 1;
    while (held.has(k)) k += 2;
    held.add(k);
  }
  const next = { arm: 0, leg: 0 };
  for (const b of SPLAT_BITS) {
    if (cutOff(b)) {
      b.anchor = { ax: a.torso.ax + b.hang.dx, ay: a.torso.ay + b.hang.dy };
      continue;
    }
    let at = a[b.role];
    if (b.role === 'arm' || b.role === 'leg') {
      let k = next[b.role];
      while (b.role === 'arm' && held.has(k)) k++;
      next[b.role] = k + 1;
      at = a[b.role](k);
    }
    b.anchor = at || a.torso;
  }
}

function bakeBit(bit) {
  const { c, g } = newCanvas(bit.sw, bit.sh);
  // Cell by cell from the piece's OWN cells: a neighbour inside its box stays out.
  for (const [x, y] of bit.cells) {
    g.fillStyle = bit.grid[y][x];
    g.fillRect(x - bit.sx, y - bit.sy, 1, 1);
  }
  return c;
}

/** The canvas a bit is drawn from. */
export function bitCanvas(bit) {
  if (!bit.canvas) bit.canvas = bakeBit(bit);
  return bit.canvas;
}

/** Bake every bit up front, so the splat never allocates a canvas inside a frame. */
export function warmSplat() {
  for (const b of SPLAT_BITS) bitCanvas(b);
  return SPLAT_BITS.length;
}

/**
 * The debris colours, by ROLE: the commonest plate grey, a lighter grey, the commonest
 * gold, blue and red found in the parts drawings. drawSplatter used to take these by
 * palette LETTER, and the letters are reassigned every time the sheet is re-imported.
 */
export const SPLAT_INKS = (() => {
  const tally = {};
  for (const b of SPLAT_BITS) {
    for (const [x, y] of b.cells) {
      const c = b.grid[y][x];
      tally[c] = (tally[c] || 0) + 1;
    }
  }
  const ranked = Object.keys(tally).sort((a, b) => tally[b] - tally[a]);
  const first = (test, skip = 0, dflt = '#8c8c8c') => ranked.filter(test)[skip] || dflt;
  const steel = first(ROLE_TEST.steel, 0, '#6c6865');
  const light = ranked.filter(ROLE_TEST.steel).sort((a, b) => tone(b).v - tone(a).v)[1] || '#b1aba4';
  return [steel, light, first(ROLE_TEST.gold, 0, '#c89343'), first(ROLE_TEST.blue, 0, '#22417d'),
    first(ROLE_TEST.red, 0, '#8c1230'), steel];
})();

/**
 * How far below its centre the lowest point of a w x h piece turned by `rot` is, and
 * how far to either side its widest point reaches. World units.
 *
 * CONTINUOUS in the angle, although the piece is only ever DRAWN at quarter turns. At a
 * quarter turn the two agree exactly, which is every moment it touches the floor: its
 * spin is planned to put it on a quarter turn at every strike (see Game.planGib). In
 * between, the true extent is never smaller than the drawn one, so a piece turning
 * near the floor is lifted by it rather than drawn sunk into it.
 */
export function halfHeight(w, h, rot) {
  return (Math.abs(Math.cos(rot)) * h + Math.abs(Math.sin(rot)) * w) / 2;
}
export function halfWidth(w, h, rot) {
  return (Math.abs(Math.cos(rot)) * w + Math.abs(Math.sin(rot)) * h) / 2;
}

/**
 * The rectangle a piece is DRAWN in: its quarter turn, and the box snapped to the art
 * grid by its corner rather than its centre.
 *
 * By the corner because a piece an odd number of art pixels across has its centre half
 * a pixel off the grid, and snapping the centre then puts every edge between two pixels
 * -- a resample. Resting, `bottom` is exactly the contact line. The renderer draws with
 * this and test-death.mjs checks it; neither has its own copy.
 */
export function pieceBox(w, h, x, y, rot) {
  const q = ((Math.round(rot / (Math.PI / 2)) % 4) + 4) % 4;
  const W = q % 2 ? h : w, H = q % 2 ? w : h;
  const left = Math.round((x - W / 2) * PX) / PX;
  const bottom = Math.round((y - H / 2) * PX) / PX;
  return { q, W, H, left, bottom };
}

/**
 * Where art pixel (ax, ay) of `frame` is in the world, relative to the point the pose
 * is drawn at -- exactly as drawSprite draws it: mirrored for `flip`, turned `q` quarter
 * turns about the cell's centre, the cell's bottom FOOT_DROP below that point.
 *
 * The one place that transform is written down for anything other than the blit. The
 * splat throws each piece from where it WAS in the last frame drawn, and a second copy
 * of this arithmetic is how a body bursts from a point beside itself.
 */
export function posePoint(frame, ax, ay, flip = false, q = 0) {
  // (ax, ay) index a pixel, so its centre is half a pixel in.
  let lx = (ax + 0.5) / PX - BODY_W / 2;   // from the cell's centre, world units, x right
  const ly = (ay + 0.5) / PX - BODY_H / 2; // ...and y DOWN, the canvas's frame inside drawSprite
  if (flip && !FRONT_FRAMES.has(frame)) lx = -lx;
  const k = ((Math.round(q) % 4) + 4) % 4;
  const c = [1, 0, -1, 0][k], s = [0, 1, 0, -1][k];
  const rx = lx * c - ly * s, ry = lx * s + ly * c;
  return { x: rx, y: BODY_H / 2 - (FOOT_DROP[frame] || 0) - ry };
}

// --- the crown's gems, found rather than typed, PER POSE -----------------------
//
// The renderer puts a travelling glint on a gem, which means it needs to know where the
// gems are. In the hand-authored sprite those were eight hand-counted column numbers that
// had to be re-measured every time the crown moved a pixel.
//
// They were then measured once, off idle0, and used for every pose -- which is why the
// glint was reported floating off his head. His crown is in a different place in every
// drawing: running he is pitched forward, landing he is crouched, tucked he is upside
// down. One measurement cannot describe all of them, and the one it does describe
// is the pose you spend the least time in.
//
// So every pose is measured on its own, on THAT drawing's own pixels: the topmost row
// with a real run of GOLD in it, which is the crown (see the test inside gemsFor).
//
// It was two other things first. Blueness: an older sheet set small blue stones in the
// crown and this hunted for them; the crown now is gold with lit points, so the blue test
// found nothing, fell through to its fallback and returned a single gem at the centre of
// the sprite. One gem is not a travelling glint, it is a stuck one. Then brightness, the
// brightest pixels in the top third of the ink, which lost to gold for the reasons given
// inside gemsFor.
function gemsFor(name) {
  const grid = FRAMES[name];
  const mid = Math.round(SPR_W / 2);
  if (!grid) return { cols: [mid], row: Math.round(SPR_H * 0.12) };

  // GOLD, not "bright". Two narrower tests were tried and both found the wrong thing:
  // the brightest pixel in the top of the cell is a specular highlight on his pauldron,
  // and the top of the INK is the tip of his sword in every pose where he raises it.
  // The crown is the one gold thing on his head, and gold is a hue, so ask for a hue.
  const gold = (col) => {
    const n = parseInt(col.slice(1), 16);
    const r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
    const mx = Math.max(r, g, b), mn = Math.min(r, g, b), d = mx - mn;
    if (mx < 110 || !d) return false;
    let h = 0;
    if (mx === r) h = 60 * (((g - b) / d) % 6);
    else if (mx === g) h = 60 * ((b - r) / d + 2);
    else h = 60 * ((r - g) / d + 4);
    if (h < 0) h += 360;
    return h >= 28 && h <= 58 && d / mx > 0.35;
  };

  // Every gold pixel, and the topmost row that has a real run of them -- his belt, the
  // cross on his tabard and the rim of his shield are gold too, and all of them are
  // below his head in every drawing.
  const rows = [];
  for (let y = 0; y < SPR_H; y++) {
    const xs = [];
    for (let x = 0; x < SPR_W; x++) if (grid[y][x] && gold(grid[y][x])) xs.push(x);
    rows.push(xs);
  }
  let row = -1;
  for (let y = 0; y < SPR_H; y++) {
    if (rows[y].length >= 3) { row = y; break; }
  }
  if (row < 0) {
    // No gold at all -- the parts frames, mostly. Put it on the ink's own centre.
    let top = -1, l = SPR_W, r2 = -1;
    for (let y = 0; y < SPR_H && top < 0; y++) {
      for (let x = 0; x < SPR_W; x++) if (grid[y][x]) { top = y; break; }
    }
    for (let x = 0; x < SPR_W; x++) {
      for (let y = 0; y < SPR_H; y++) if (grid[y][x]) { if (x < l) l = x; if (x > r2) r2 = x; break; }
    }
    return { cols: [Math.round((l + r2) / 2)], row: Math.max(0, top) + 3 };
  }

  // THE ROW THE COLUMNS COME FROM IS THE ROW REPORTED. They were taken from a twelve-row
  // band and reported two rows lower, which is fine on a crown drawn square on and wrong
  // on every pose where it is tilted: on run2 and land the reported row had no ink within
  // three pixels of the reported column, so the glint sat beside his head rather than on
  // it. The densest gold row in the band is the band itself.
  let bestRow = row, bestN = 0;
  for (let y = row; y < Math.min(SPR_H, row + 12); y++) {
    if (rows[y].length > bestN) { bestN = rows[y].length; bestRow = y; }
  }
  row = bestRow;
  const cols = [];
  for (let y = Math.max(0, row - 1); y <= Math.min(SPR_H - 1, row + 1); y++) cols.push(...rows[y]);
  cols.sort((a, b) => a - b);
  const gems = [];
  let run = [cols[0]];
  const flush = () => gems.push(Math.round(run.reduce((t, v) => t + v, 0) / run.length));
  for (let i = 1; i < cols.length; i++) {
    if (cols[i] - cols[i - 1] <= 4) run.push(cols[i]);
    else { flush(); run = [cols[i]]; }
  }
  flush();
  return { cols: gems.length ? gems : [mid], row };
}

export const CROWN_GEMS = Object.fromEntries(NAMES.map((n) => [n, gemsFor(n)]));

// --- the speed afterimage ---------------------------------------------------------
//
// Flat silhouettes of him, one tone per atlas, which the renderer lays down behind him
// on the path he has just taken (see afterimage.js). Baked at load -- a lazily-built
// atlas is a canvas allocation and a full rasterisation inside a frame, which is the
// mistake the font made once already.
//
// THE TWO EFFECTS BEFORE THIS ONE CAME APART FROM HIM IN DIFFERENT WAYS.
//
// The first silhouette trail drew four copies of the CURRENT frame 9 ms apart along -v,
// clamped at 6 and 7 units a copy: on a launch they hung 28 units -- his height -- under
// his boots, a straight line where his path curves. Each copy's cell bottom sat on his
// feet where drawSprite lowers the cell by FOOT_DROP, and no copy took the landing squash
// or the tuck's spin, so even the nearest was a different shape from him. The user saw it
// trailing far behind him, where it should have been on top of him.
//
// It was replaced by a halo: rings of light round his outline, placed by the code that
// places the sprite. That fixed the placement and lost the look, and the roll broke it.
// The tuck turned in quarter turns about the CELL's centre, twelve units above the ball
// of him, so every 71 ms the ball jumped 14 to 21 units (57 to 86 px at zoom 1, measured
// frame by frame at 160 Hz) sideways to his travel. The halo was drawn only where he IS,
// its three copies all in his current rotation and lagged 1.5 units at most along -v, so
// at each quarter turn the lit outline jumped with the ball and nothing was left where he
// had been, and its "trailing" side pointed up to 153 degrees away from where the ball had
// actually come from (over 70 at three of six turns measured) -- the new rotation drawn at
// places he never was in it.
//
// So: the old silhouettes, in the old tone and alphas, each drawn with the state he was
// drawn in at that moment of his path -- pose, facing, squash and quarter turn -- through
// placeCell, the code that places the sprite. And the tuck turns about the ball of him
// now (SPIN_PIVOT): with the old pivot those faithful copies stood a ball's width off him
// for two or three frames after every quarter turn.
//
// From the rows the DRAWING atlas holds (atlasRows), not the whole grid: a standing pose's
// shield point under the landing line is left out of the sprite, so it is left out of the
// silhouette too, and a copy is exactly the shape he is drawn as.
const ghosts = {};

function buildGhost(flip, colour) {
  const grids = flip ? FRAMES_LEFT : FRAMES;
  // Whole numbers (newCanvas), so the headless canvas keeps its size as an integer (a heap
  // double there slows every frame of the process; a browser truncates it anyway).
  const { c, g } = newCanvas(NAMES.length * SPR_W, SPR_H);
  g.fillStyle = colour;
  NAMES.forEach((name, i) => {
    const buf = grids[name];
    const rows = atlasRows(name);
    for (let y = 0; y < rows; y++) {
      let x = 0;
      while (x < SPR_W) {
        if (!buf[y][x]) { x++; continue; }
        let run = 1;
        while (x + run < SPR_W && buf[y][x + run]) run++;
        g.fillRect(i * SPR_W + x, y, run, 1);
        x += run;
      }
    }
  });
  return c;
}

export function ghostAtlas(flip, light) {
  const key = (flip ? 'f' : 'n') + (light ? 'l' : 'd');
  if (!ghosts[key]) ghosts[key] = buildGhost(flip, light ? '#ffffff' : '#000000');
  return ghosts[key];
}

/** Build every silhouette up front, so none is ever allocated inside a frame. */
export function warmGhosts() {
  for (const f of [false, true]) for (const l of [false, true]) ghostAtlas(f, l);
  return 4;
}

/**
 * A flat silhouette of `frame`, placed exactly as drawSprite places the frame for the
 * same arguments. `light` is white for a dark backdrop, black for a light one.
 */
export function drawGhost(ctx, frame, cx, by0, flip = false, spin = 0, sq = 0, light = true) {
  const i = INDEX.get(frame);
  if (i === undefined) return;
  if (FRONT_FRAMES.has(frame)) flip = false;
  placeCell(ctx, ghostAtlas(flip, light), i * SPR_W, frame, cx, by0, spin, sq, flip);
}

/**
 * Draw a frame centred horizontally on `cx`, with its feet on `by`.
 *
 * `cx`/`by` and the destination size are WORLD units; the source rect is the atlas in
 * PIXELS. SPR is BODY * PX, so at zoom 1 this is an exact 1:1 blit and at zoom 2 an
 * exact 2x magnification, both pixel-perfect. The non-integer zooms between them are
 * the only place he is ever resampled.
 *
 * The left-facing atlas is a MIRROR of the right-facing one. This sheet has one facing,
 * unlike the first, so his sword and shield swap hands when he turns around. That is the
 * ordinary compromise for a side-scroller and reads fine in motion; the alternative is a
 * second, left-facing drawing of every side-on pose.
 */
export function drawSprite(ctx, frame, cx, by0, flip = false, spin = 0, sq = 0) {
  const i = INDEX.get(frame);
  if (i === undefined) return;
  if (FRONT_FRAMES.has(frame)) flip = false;
  placeCell(ctx, spriteAtlas(flip), i * SPR_W, frame, cx, by0, spin, sq, flip);
}

/**
 * The point a somersault turns about: the middle of the ball he curls into, in art pixels
 * from the cell's centre (x right, y down), per facing.
 *
 * The tuck used to turn about the middle of its CELL. The cell is 63 x 53 units, sized
 * for a sword arm and a shield, and the ball of him sits in the bottom of it, twelve and a
 * half units under that point -- so each quarter turn swung the ball round a circle
 * twenty-five units across: 17.5 units at every turn, 14 times a second, and on the half
 * turn twenty-five units above his feet. The roll read as a man jittering
 * about the screen, not turning over; anything laid on him (the halo, then the
 * afterimage's copies from before a turn) showed the hop as a second ball beside him.
 * Turned about the ball's own middle he rolls in place, over his feet.
 *
 * Rounded DOWN to a whole art pixel, so the turned drawing still lands on the art-pixel
 * grid (the pivot is on the same grid as the cell's centre was), and so the half turn
 * sits one art pixel above his soles rather than one below. Only the somersault: the
 * death's tumble turns the fall pose, which fills its cell, about the cell's centre.
 */
function spinPivot(grid) {
  let x0 = SPR_W, y0 = SPR_H, x1 = -1, y1 = -1;
  for (let y = 0; y < SPR_H; y++) {
    for (let x = 0; x < SPR_W; x++) {
      if (!grid[y][x]) continue;
      if (x < x0) x0 = x;
      if (x > x1) x1 = x;
      if (y < y0) y0 = y;
      if (y > y1) y1 = y;
    }
  }
  return [Math.floor((x0 + x1 + 1) / 2 - SPR_W / 2), Math.floor((y0 + y1 + 1) / 2 - SPR_H / 2)];
}
const SPIN_POSES = ['tuck'];
export const SPIN_PIVOT = {
  right: Object.fromEntries(SPIN_POSES.map((n) => [n, spinPivot(FRAMES[n])])),
  left: Object.fromEntries(SPIN_POSES.map((n) => [n, spinPivot(FRAMES_LEFT[n])])),
};

/**
 * Where a pose's cell goes on screen, for the sprite and for anything that must take his
 * exact shape (the afterimage's silhouettes): one function, so the two cannot drift apart
 * the way the first silhouette trail did from him. `img` is any atlas laid out like the
 * sprite's, one SPR_W x SPR_H cell a pose.
 */
export function placeCell(ctx, img, sx, frame, cx, by0, spin, sq, flip) {
  // Stand him on his boots, not on his shield's point or a sword tip. See FOOT_DROP.
  const by = by0 + (FOOT_DROP[frame] || 0);

  if (spin) {
    // Quarter turns only. Rotating pixel art by an arbitrary angle resamples it and
    // turns the outline to mush.
    const q = ((Math.round(spin) % 4) + 4) % 4;
    if (q) {
      // A somersault turns about the ball of him, anything else about the cell's centre
      // (both offsets 0, every argument as it always was). See SPIN_PIVOT.
      const pv = (flip ? SPIN_PIVOT.left : SPIN_PIVOT.right)[frame];
      const ox = pv ? pv[0] / PX : 0, oy = pv ? pv[1] / PX : 0;
      ctx.save();
      ctx.translate(cx + ox, by - BODY_H / 2 + oy);
      ctx.rotate((q * Math.PI) / 2);
      ctx.drawImage(img, sx, 0, SPR_W, SPR_H, -BODY_W / 2 - ox, -BODY_H / 2 - oy, BODY_W, BODY_H);
      ctx.restore();
      return;
    }
  }

  // Squash and stretch preserves volume and keeps the feet planted.
  //
  // Planted means the BOOTS, and the rows under them squash with the rest of the drawing.
  // Lowered by the unsquashed drop, a standing pose landed drop x (1 - ky) too low: in the
  // tail of a landing squash -- the idle or the stride that follows the 0.12 s landing
  // pose, still at a quarter squash -- that put his soles a screen pixel into the ledge
  // at 1.25, 1.5 and 1.75. Only for poses that stand on something; an airborne pose's
  // drop is not a foot, and it stays where it was.
  const kx = 1 + sq * -0.22, ky = 1 + sq * 0.26;
  const w = BODY_W * kx, h = BODY_H * ky;
  const bs = GROUND_POSES.has(frame) ? by0 + (FOOT_DROP[frame] || 0) * ky : by;
  // A standing pose has nothing under its boot row in the atlas (atlasRows), so standing,
  // nothing of him is drawn below the landing line.
  ctx.drawImage(img, sx, 0, SPR_W, SPR_H, cx - w / 2, bs - h, w, h);
}

export function resetSpriteCache() {
  atlas = null;
  atlasFlip = null;
  for (const k of Object.keys(ghosts)) delete ghosts[k];
}
