// Finding the shield in a drawing of the Duke.
//
// WHAT THIS IS LEFT OF
//
// src/render/shieldstamp.js used to find the red field in every cell of the sprite sheet,
// measure its box, and draw a whole computed heater into it -- rim, field and a rider --
// because no sheet before the third had the arms of the Grand Duchy on it. The third one
// does, drawn in every pose at the angle that pose holds the shield, so the game does not
// paint shields any more and that file is gone.
//
// The MEASURING half is still worth having: it is what lets a tool crop the shield out of
// all eighteen cells and put them on one sheet, which is how the stamper's worst bug was
// found. Nothing here draws.
//
// resolve(pal) must be called before anything else: what counts as red and gold is decided
// per sheet, because the palette is generated and assigns keys by population.

export function resolve(pal) {
  FIELD = redKeys(pal);
  CRIMSON = crimsonKeys(pal);
  GOLD = new Set(Object.entries(pal).filter(([k, hex]) => {
    if (FIELD.has(k)) return false;
    const n = parseInt(hex.slice(1), 16);
    const r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
    return r > 90 && g > 60 && b < g;      // golds, tans and steels-with-warmth
  }).map(([k]) => k));
}

// The field colour of the shield on the imported sheet. Everything here keys off it.
//
// RESOLVED FROM THE PALETTE, not hard-coded. It used to be the literal 'G', which was
// the red on one particular sheet; the palette is generated per sheet now and assigns
// keys by population, so 'G' means whatever happened to be seventh most common. A key
// that means red on one import means gold on the next, silently.
let FIELD = new Set(['G']);          // the red field, resolved per sheet
let GOLD = new Set(['C', 'B', 'A', 'E']);   // rim and any old device
// The subset of FIELD that is a true crimson rather than a warm brown. See CRIMSON_MIN.
let CRIMSON = new Set();

/** Every key in a palette that is unmistakably red. */
function redKeys(pal) {
  return new Set(Object.entries(pal).filter(([, hex]) => {
    const n = parseInt(hex.slice(1), 16);
    const r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
    // Tight on purpose. A looser test (r-g > 35 alone) also matches every tan and gold
    // on the sheet -- his crown, his beard highlights, the trim on his tabard -- and
    // the face got wiped to one of THOSE: a gold shield with a rider on it.
    return r > 55 && r - g > 30 && g < r * 0.62 && b < r * 0.60;
  }).map(([k]) => k));
}

/** Every key that is a true crimson: red hue, properly saturated. */
function crimsonKeys(pal) {
  return new Set(Object.entries(pal).filter(([, hex]) => {
    const n = parseInt(hex.slice(1), 16);
    const r = (n >> 16) & 255, g = (n >> 8) & 255, b = n & 255;
    const mx = Math.max(r, g, b), mn = Math.min(r, g, b), d = mx - mn;
    if (!d || mx === 0) return false;
    let hue = 0;
    if (mx === r) hue = 60 * (((g - b) / d) % 6);
    else if (mx === g) hue = 60 * ((b - r) / d + 2);
    else hue = 60 * ((r - g) / d + 4);
    if (hue < 0) hue += 360;
    return hue <= 14 && d / mx > 0.5;
  }).map(([k]) => k));
}

// Below this many pixels the red is a scabbard strap or a fleck of cloak, not a shield.
const MIN_FACE = 40;

/**
 * How much of a candidate blob must be true crimson for it to be a SHIELD.
 *
 * HIS BEARD IS RED. The palette is generated by population and this sheet's reds run from
 * a crimson field through to the browns of an auburn beard, and the loose test that
 * separates a shield from a tabard cannot tell those apart: on three cells -- the
 * somersault, the knockout and the severed head -- the largest "red" blob in the drawing
 * was his HAIR, and a coat of arms was stamped neatly over his face. It shipped.
 *
 * Hue separates them cleanly and the gap is not a knife edge. Measured over all eighteen
 * cells, the fraction of each winning blob that is strict crimson is 0.78 to 0.92 on every
 * real shield and 0.28 to 0.36 on the three heads. Anything in the middle of that gap
 * works; a blob that fails it is not a shield and the frame is left alone.
 */
const CRIMSON_MIN = 0.6;

/**
 * The shield's face in one frame: the largest connected run of field colour, PLUS
 * anything it encloses.
 *
 * The enclosed part matters. The gold cross sits in the middle of the field and splits
 * it, so the red alone is a ring with a cross-shaped hole in it. Stamping only onto red
 * would paint the rider with a cross-shaped bite taken out of him. Anything the flood
 * cannot reach from outside the box is inside the shield, and the cross is the only
 * thing there.
 */
export function shieldFace(frame, sprW) {
  const H = frame.length;
  const seen = Array.from({ length: H }, () => new Array(sprW).fill(false));
  let best = null;

  for (let y = 0; y < H; y++) {
    for (let x = 0; x < sprW; x++) {
      if (seen[y][x] || !FIELD.has(frame[y][x])) continue;
      const stack = [[x, y]];
      seen[y][x] = true;
      const cells = [];
      let crim = 0;
      let bx0 = Infinity, by0 = Infinity, bx1 = -1, by1 = -1;
      while (stack.length) {
        const [cx, cy] = stack.pop();
        cells.push([cx, cy]);
        if (CRIMSON.has(frame[cy][cx])) crim++;
        if (cx < bx0) bx0 = cx; if (cx > bx1) bx1 = cx;
        if (cy < by0) by0 = cy; if (cy > by1) by1 = cy;
        for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) {
          const nx = cx + dx, ny = cy + dy;
          if (nx < 0 || ny < 0 || nx >= sprW || ny >= H) continue;
          if (seen[ny][nx] || !FIELD.has((frame[ny] || '')[nx])) continue;
          seen[ny][nx] = true;
          stack.push([nx, ny]);
        }
      }
      // A blob that is mostly warm brown is hair, not heraldry. Rejected HERE rather than
      // after the fact, so a frame holding both his beard and his shield still finds the
      // shield instead of stopping at whichever is larger.
      if (CRIMSON.size && crim / cells.length < CRIMSON_MIN) continue;
      if (!best || cells.length > best.cells.length) best = { cells, bx0, by0, bx1, by1 };
    }
  }
  if (!best || best.cells.length < MIN_FACE) return null;

  let { bx0, by0, bx1, by1 } = best;
  let w = bx1 - bx0 + 1;
  const h = by1 - by0 + 1;

  // The face is the field's per-row SPAN, not the field itself.
  //
  // The red is a ring: the gold cross splits it, so the field alone has a cross-shaped
  // hole and stamping into it paints the rider with a bite taken out of him. The obvious
  // repair -- add whatever the outside cannot reach -- does not work here, and it is
  // worth saying why, because it looked right and rendered wrong. The shield's rim is
  // shaded in the same browns as his belt and boots, and that shading touches the
  // background, so a flood from outside walks along the rim, round behind the cross and
  // into it. The cross came out "not enclosed" and survived the wipe.
  //
  // Spans have no such hole to fall through. The rim is GOLD and sits outside the red,
  // so on any row that crosses the shield the leftmost and rightmost red pixels are the
  // field's own edges and everything between them -- cross included -- is shield face.
  const mask = Array.from({ length: h }, () => new Array(w).fill(false));
  //
  // Scanned off the FRAME across the blob's columns, not off the blob's own cells. The
  // cross reaches the rim low on the shield, cutting the field into two components, and
  // the strip on the far side is a component of its own. Measuring spans from the largest
  // blob alone stopped at the cross and left the bottom half of it standing.
  const lo = new Array(h).fill(Infinity);
  const hi = new Array(h).fill(-1);
  for (let y = 0; y < h; y++) {
    const row = frame[by0 + y] || '';
    // Seed from the field inside the blob's own box...
    for (let x = bx0; x <= bx1; x++) {
      if (!FIELD.has(row[x])) continue;
      if (x - bx0 < lo[y]) lo[y] = x - bx0;
      if (x - bx0 > hi[y]) hi[y] = x - bx0;
    }
    if (hi[y] < 0) continue;
    // ...then walk OUT THROUGH the device.
    //
    // The cross reaches the rim low on the shield, cutting the field into separate
    // components, and the strip on the far side is a component of its own that falls
    // outside the largest blob's bounding box. Measuring spans only inside that box
    // stopped at the cross and left a gold bar standing down the right of the shield on
    // the profile poses -- which is exactly what was reported.
    //
    // Walking through gold and only committing when FIELD is found again is what tells
    // a cross from a rim: past the cross there is more red, so the span extends; past
    // the rim there is armour or background, so it does not, and the rim survives.
    const walk = (dir) => {
      let x = bx0 + (dir < 0 ? lo[y] : hi[y]) + dir;
      while (x >= 0 && x < sprW && (FIELD.has(row[x]) || GOLD.has(row[x]))) {
        if (FIELD.has(row[x])) {
          if (x - bx0 < lo[y]) lo[y] = x - bx0;
          if (x - bx0 > hi[y]) hi[y] = x - bx0;
        }
        x += dir;
      }
    };
    walk(-1);
    walk(1);
  }

  // Spans may now reach outside the blob's box, so the face grows with them.
  let ex0 = 0, ex1 = w - 1;
  for (let y = 0; y < h; y++) {
    if (hi[y] < 0) continue;
    if (lo[y] < ex0) ex0 = lo[y];
    if (hi[y] > ex1) ex1 = hi[y];
  }
  if (ex0 !== 0 || ex1 !== w - 1) {
    const shift = -ex0;
    const nw = ex1 - ex0 + 1;
    for (let y = 0; y < h; y++) {
      if (hi[y] < 0) continue;
      lo[y] += shift;
      hi[y] += shift;
    }
    bx0 += ex0;
    w = nw;
    mask.length = 0;
    for (let y = 0; y < h; y++) mask.push(new Array(w).fill(false));
  }

  // Heal rows the shield does not own outright -- CONSERVATIVELY.
  //
  // A band across the middle of the front pose has almost no red in it: the gold rim
  // catches the light there and the highlight is drawn in tans that also serve as skin.
  // Measured literally that band is a notch bitten out of the middle of the shield, and
  // a rider stamped through it loses the horse's barrel and back legs.
  //
  // The first version of this widened every row to the widest row within three, which
  // fixed the notch and ATE THE RIM. A heater shield curves in at the top, so its first
  // few rows are genuinely narrow; widening them to match the rows below punched the
  // gold corners out of the shield. That is the "missing a piece" that was reported.
  //
  // So a row is only filled when it is a genuine local minimum -- content above AND
  // below -- and only out to the NARROWER of its two neighbours. An interpolation, not
  // a maximum. A row at either end of the shield has no neighbour on one side and is
  // left exactly as measured, which is what preserves the curve and the rim.
  const HEAL = 3;
  const near = (y, dir) => {
    for (let d = 1; d <= HEAL; d++) {
      const j = y + d * dir;
      if (j < 0 || j >= h) return null;
      if (hi[j] >= 0) return j;
    }
    return null;
  };
  const lo2 = lo.slice(), hi2 = hi.slice();
  for (let y = 0; y < h; y++) {
    if (hi[y] < 0) continue;
    const up = near(y, -1), dn = near(y, 1);
    if (up === null || dn === null) continue;
    lo2[y] = Math.min(lo[y], Math.max(lo[up], lo[dn]));
    hi2[y] = Math.max(hi[y], Math.min(hi[up], hi[dn]));
  }
  for (let y = 0; y < h; y++) {
    if (hi2[y] < 0) continue;
    for (let x = lo2[y]; x <= hi2[y]; x++) mask[y][x] = true;
  }

  return { x: bx0, y: by0, w, h, mask };
}

/**
 * The shield's full extent INCLUDING its rim.
 *
 * shieldFace() measures the red FIELD, which stops inside the gold. Drawing a whole
 * shield into that box leaves the sheet's own rim standing around it -- a second border
 * ringing the first, which reads as a picture frame rather than a shield. The rim is
 * gold and only a few pixels thick, so the box grows outward through gold and no
 * further.
 */
export function shieldBox(frame, sprW, face) {
  const f = face || shieldFace(frame, sprW);
  if (!f) return null;
  const RIM_MAX = 4;
  let x0 = f.x, y0 = f.y, x1 = f.x + f.w - 1, y1 = f.y + f.h - 1;
  const goldAt = (x, y) => {
    const row = frame[y];
    return !!row && GOLD.has(row[x]);
  };
  const anyGoldCol = (x) => {
    for (let y = f.y; y < f.y + f.h; y++) if (goldAt(x, y)) return true;
    return false;
  };
  const anyGoldRow = (y) => {
    for (let x = f.x; x < f.x + f.w; x++) if (goldAt(x, y)) return true;
    return false;
  };
  for (let n = 0; n < RIM_MAX && x0 > 0 && anyGoldCol(x0 - 1); n++) x0--;
  for (let n = 0; n < RIM_MAX && x1 < sprW - 1 && anyGoldCol(x1 + 1); n++) x1++;
  for (let n = 0; n < RIM_MAX && y0 > 0 && anyGoldRow(y0 - 1); n++) y0--;
  for (let n = 0; n < RIM_MAX && y1 < frame.length - 1 && anyGoldRow(y1 + 1); n++) y1++;
  return { x: x0, y: y0, w: x1 - x0 + 1, h: y1 - y0 + 1 };
}

