// Guard for the character art.
//
// The art is IMPORTED now (src/render/vytisart.js, generated by tools/import-sprite.mjs
// from the artist's sheet), so this no longer checks the things a procedural sprite
// needed checking for -- head centring, limb rasterisation, per-pose palette coverage.
// It checks the things that can still silently go wrong between a good sheet and a good
// frame on screen: the resolution identity, the feet, the facings, and unmapped colours.
//
// What it CANNOT check is whether the art is good. `node tools/shot.mjs --sprite=... `
// is for that.

import { installDom } from './headless.mjs';

installDom();

const S = await import('../src/render/sprites.js');
const ART = await import('../src/render/vytisart.js');
const { PX } = await import('../src/game/constants.js');

let bad = 0;
const fail = (m) => { console.log('  FAIL ' + m); bad++; };
const ok = (m) => console.log('  ok   ' + m);

// --- the resolution identity ---------------------------------------------------
//
// One art pixel must be exactly one backing-store pixel. Break this and every frame is
// resampled on its way to the screen, which is the difference between the reference and
// a blurry impression of it.
if (S.SPR_W !== S.BODY_W * PX || S.SPR_H !== S.BODY_H * PX) {
  fail(`${S.SPR_W}x${S.SPR_H} art against ${S.BODY_W}x${S.BODY_H} world at PX ${PX}`);
} else {
  ok(`${S.SPR_W}x${S.SPR_H} art = ${S.BODY_W}x${S.BODY_H} world x PX ${PX}, 1:1`);
}

// He has to fit between two floors, which is the constraint that has shaped this
// character since the beginning: FLOOR_H - PLAT_THICK of clear air above a platform.
const { FLOOR_H, PLAT_THICK } = await import('../src/game/constants.js');
const gap = FLOOR_H - PLAT_THICK;
if (S.BODY_H > gap) {
  console.log(`  note  he is ${S.BODY_H} world units tall against a ${gap}-unit gap ` +
    `-- he overlaps the platform above by ${(S.BODY_H - gap).toFixed(2)}`);
} else {
  ok(`${S.BODY_H} world units tall, inside the ${gap}-unit gap with ${(gap - S.BODY_H).toFixed(2)} to spare`);
}

// --- the imported sheet ---------------------------------------------------------
if (!ART.FRAMES.length) fail('the imported sheet has no frames');
for (const [i, f] of ART.FRAMES.entries()) {
  if (f.length !== ART.SPR_H) fail(`imported frame ${i} is ${f.length} rows, not ${ART.SPR_H}`);
  for (const row of f) if (row.length > ART.SPR_W) fail(`imported frame ${i} has a ${row.length}-column row`);
}

// Every character in the art must have a colour. An unmapped key renders magenta, which
// is loud, but a test that says which key is better than a screenshot that says where.
const used = new Set();
for (const f of ART.FRAMES) for (const row of f) for (const ch of row) if (ch !== '.') used.add(ch);
const orphans = [...used].filter((ch) => !ART.PAL[ch]);
if (orphans.length) fail(`art uses ${orphans.map((c) => `'${c}'`).join(', ')} with no palette entry`);
else ok(`${used.size} palette keys used, all mapped`);

// --- the poses ------------------------------------------------------------------
const NAMES = S.NAMES;
if (!NAMES.length) fail('no poses');

// FEET ON THE FLOOR. Every pose is positioned by its bottom edge, so a frame whose
// lowest drawn row is not the last row hovers, and one that would have drawn past it has
// been silently clipped. This is the bug that had the old sprite standing on a
// one-pixel smear for weeks.
for (const name of NAMES) {
  const grid = S.FRAMES[name];
  let lowest = -1, highest = -1;
  for (let y = 0; y < S.SPR_H; y++) {
    if (grid[y].some(Boolean)) { if (highest < 0) highest = y; lowest = y; }
  }
  if (lowest < 0) { fail(`${name} draws nothing at all`); continue; }
  if (lowest !== S.SPR_H - 1) fail(`${name} floats: its lowest row is ${lowest}, the cell ends at ${S.SPR_H - 1}`);
  if (highest === 0 && name !== 'splat') {
    // Touching the top is fine for a tall pose; worth reporting, not failing.
    console.log(`  note  ${name} reaches the top row of its cell`);
  }
}
ok(`${NAMES.length} poses, every one standing on the bottom row`);

// ON HIS BOOTS, NOT HIS SHIELD. The bottom row is the importer's business; which row he
// STANDS on is FOOT_DROP's, and that is a question about what the lowest pixels are.
//
// FOOT_INK answered it by counting ink, and it was tuned on a sheet whose lowest pixel was
// a sword tip. Three imports later the lowest pixel of every standing pose was the POINT
// OF HIS SHIELD, the count took that for a footprint, and he stood a half world unit over
// every ledge -- two screen pixels of sky under his soles at zoom 1, four at zoom 2 --
// with nothing failing, because nothing compared the anchor with where his boots are.
//
// Where his boots end is something only a person can say, so a person said it: these are
// the rows his lowest BOOT pixel is on in each drawing, read by eye off x8 crops of this
// import (the boots' soles, the shield's point beside them). A re-import that moves his
// feet fails here, on purpose. Look at the new cells' bottom rows blown up
// (`node tools/shot.mjs --sprite=idle0,idle1 --scale=8`) and write down what you see.
{
  const BOOT_ROW = {
    idle0: 209, idle1: 208, idle2: 209, idle3: 208, idle4: 208,
    run0: 211, run1: 211, run2: 211, land: 211,
  };
  const grounded = new Set([...S.IDLE_CYCLE, ...S.RUN_CYCLE, 'land']);
  const wrong = [];
  for (const n of grounded) {
    const row = S.SPR_H - 1 - S.FOOT_DROP[n] * PX;
    if (BOOT_ROW[n] === undefined) wrong.push(`${n} stands on a ledge and has no measured boot row`);
    else if (row !== BOOT_ROW[n]) {
      wrong.push(`${n} is anchored on row ${row}, his boots end on row ${BOOT_ROW[n]} -- ` +
        (row > BOOT_ROW[n] ? `his soles hover ${row - BOOT_ROW[n]} art px` : `his soles sink ${BOOT_ROW[n] - row} art px`));
    }
  }
  if (wrong.length) wrong.forEach(fail);
  else ok(`${grounded.size} standing poses anchored on their boots, not the shield's point`);

  // ...and the anchor is what reaches the SCREEN, at every rest zoom, facing either way,
  // and in the tail of the landing squash. drawSprite is drawn exactly as the renderer
  // draws it -- the world scale is zoom x PX, the ledge's top on a whole world unit -- and
  // every column whose own lowest ink is the anchor row must end on the screen row
  // directly over the ledge. Neither one row of sky under it nor one row into the ledge.
  //
  // The rest zooms are every whole world scale between the widest arena and the
  // narrowest, which is what the arena quantises to.
  const { VW, WALL_W, ARENA_HALF_MIN, ARENA_HALF_MAX } = await import('../src/game/constants.js');
  const { HeadlessCanvas } = await import('./headless.mjs');
  const kLo = Math.round(PX * VW / (2 * ARENA_HALF_MAX + 2 * WALL_W));
  const kHi = Math.round(PX * VW / (2 * ARENA_HALF_MIN + 2 * WALL_W));
  const LEDGE = 60, CX = 40;                     // world units; any whole ledge height
  const off = [];
  let checked = 0;
  for (let k = kLo; k <= kHi; k++) {
    const cv = new HeadlessCanvas(Math.ceil((CX + S.BODY_W) * k), (LEDGE + 16) * k);
    const g = cv.getContext('2d');
    for (const n of grounded) {
      const row = S.SPR_H - 1 - S.FOOT_DROP[n] * PX;
      const grid = S.FRAMES[n];
      const lowest = (x) => {
        let y = S.SPR_H - 1;
        while (y >= 0 && x >= 0 && x < S.SPR_W && !grid[y][x]) y--;
        return y;
      };
      // Columns INSIDE a sole: their neighbours end on the anchor row too. At 1.25 an art
      // pixel is a screen pixel and a quarter, and the column a screen pixel lands in at
      // the edge of a boot depends on how the canvas rounds its box -- this one rounds it
      // to whole pixels, a browser does not -- so an edge column can sample the shield's
      // point beside it. That is a question about columns; this test asks about rows.
      const sole = [];
      for (let x = 0; x < S.SPR_W; x++) {
        if (lowest(x) === row && lowest(x - 1) === row && lowest(x + 1) === row) sole.push(x);
      }
      // The idles face the viewer and are never flipped, so they have one facing to check.
      for (const flip of S.FRONT_FRAMES.has(n) ? [false] : [false, true]) {
        for (const sq of [0, -0.24]) {   // -0.24: what is left of the squash as `land` ends
          cv.data.fill(0);
          g.setTransform(k, 0, 0, k, 0, 0);
          S.drawSprite(g, n, CX, LEDGE, flip, 0, sq);
          const kx = 1 + sq * -0.22;
          const mirrored = flip && !S.FRONT_FRAMES.has(n);
          let bad = 0;
          for (const ax of sole) {
            const col = mirrored ? S.SPR_W - 1 - ax : ax;
            const sx = Math.floor(k * (CX + ((col + 0.5) / PX - S.BODY_W / 2) * kx));
            let low = -1;
            const d = cv.data;
            for (let y = 0; y < cv.height; y++) if (d[(y * cv.width + sx) * 4 + 3]) low = y;
            if (low !== LEDGE * k - 1) bad++;
            checked++;
          }
          if (bad) off.push(`${n}${mirrored ? ' (left)' : ''} at zoom ${k / PX}${sq ? ` squashed ${sq}` : ''}: ${bad} of ${sole.length} sole columns off the ledge`);
        }
      }
    }
  }
  if (off.length) off.slice(0, 12).forEach(fail);
  else ok(`${checked} sole columns land on the row over the ledge at every rest zoom (${kLo / PX}-${kHi / PX}), both facings, squashed or not`);

  // ...and NOTHING of him lands on or under the landing line while he stands. The check
  // above looks only at the sole columns, so it passed while the point of his heater
  // shield, held low beside him in every idle, hung two or three art rows under the line
  // -- drawn in front of the ledge's lit top rows, so on a flat deck (DOWNTOWN's gallery,
  // STORM's cloud, the ground) the V of the shield notched the one line a player tracks.
  // Here every column counts: any ink on the ledge's first row or below it fails, at every
  // rest zoom, both facings, through the landing squash -- the whole of it for `land`,
  // and what is left of it for the idles and strides that follow.
  const under = [];
  let drawn = 0;
  for (let k = kLo; k <= kHi; k++) {
    const cv = new HeadlessCanvas(Math.ceil((CX + S.BODY_W) * k), (LEDGE + 16) * k);
    const g = cv.getContext('2d');
    for (const n of grounded) {
      for (const flip of S.FRONT_FRAMES.has(n) ? [false] : [false, true]) {
        for (const sq of n === 'land' ? [-1, -0.5, -0.24, 0] : [-0.24, -0.12, 0]) {
          cv.data.fill(0);
          g.setTransform(k, 0, 0, k, 0, 0);
          S.drawSprite(g, n, CX, LEDGE, flip, 0, sq);
          let ink = 0, rows = 0;
          const d = cv.data;
          for (let y = LEDGE * k; y < cv.height; y++) {
            let r = 0;
            for (let x = 0; x < cv.width; x++) if (d[(y * cv.width + x) * 4 + 3]) r++;
            if (r) { ink += r; rows++; }
          }
          drawn++;
          if (ink) {
            under.push(`${n}${flip ? ' (left)' : ''} at zoom ${k / PX}${sq ? ` squashed ${sq}` : ''}: ` +
              `${ink} px on ${rows} screen row(s) at or under the landing line`);
          }
        }
      }
    }
  }
  if (under.length) {
    under.slice(0, 12).forEach(fail);
    if (under.length > 12) console.log(`  ...and ${under.length - 12} more`);
  } else {
    ok(`${drawn} standing draws put nothing under the landing line, every rest zoom, both facings, through the landing squash`);
  }
}

// Both facings must exist and must DIFFER for every profile pose.
//
// If they came out identical he would walk left while still facing right, which reads as
// a bug long before anyone works out why. It catches a broken mirror and it would catch
// an import that picked up only half a two-facing sheet.
let identical = 0;
for (const name of NAMES) {
  if (S.FRONT_FRAMES.has(name)) continue;
  if (JSON.stringify(S.FRAMES[name]) === JSON.stringify(S.FRAMES_LEFT[name])) identical++;
}
if (identical) fail(`${identical} profile pose(s) are identical in both facings -- half the sheet is missing`);
else ok('every profile pose faces the other way when flipped');

// The run cycle has to be real frames, and distinct ones, or he moonwalks.
for (const n of S.RUN_CYCLE) if (!NAMES.includes(n)) fail(`RUN_CYCLE names ${n}, which is not a pose`);
const runSigs = new Set(S.RUN_CYCLE.map((n) => JSON.stringify(S.FRAMES[n])));
if (runSigs.size !== S.RUN_CYCLE.length) {
  fail(`the ${S.RUN_CYCLE.length}-frame run cycle has only ${runSigs.size} distinct drawings`);
} else {
  ok(`${S.RUN_CYCLE.length}-frame run cycle, every frame distinct`);
}

for (const n of S.FRONT_FRAMES) if (!NAMES.includes(n)) fail(`FRONT_FRAMES names ${n}, which is not a pose`);

// The crown gems drive the glint, and there is one set PER POSE.
//
// It used to be one measurement off idle0 applied to all nineteen drawings, which is why
// the glint was reported floating off his head: his crown is somewhere different in every
// one of them, and the pose that measurement described is the one you spend the least
// time in.
{
  const gems = S.CROWN_GEMS;
  const bad = [];
  // The parts frames have no crown and no glint drawn on them; everything he is alive in
  // must have one, and it must be ON him.
  const live = NAMES.filter((n) => !['parts0', 'parts1', 'dazed', 'splat'].includes(n));
  for (const n of live) {
    const g = gems[n];
    if (!g || !g.cols || !g.cols.length) { bad.push(`${n}: none found`); continue; }
    if (g.cols.some((x) => x < 0 || x >= S.SPR_W)) bad.push(`${n}: a gem is outside the sprite`);
    if (g.row < 0 || g.row >= S.SPR_H) bad.push(`${n}: row ${g.row} is outside the sprite`);
    // ON HIM: the row the glint sits on must actually have ink in this drawing, or it is
    // hanging in the air beside him. This is the check the old one could not make,
    // because a single shared row cannot be on nineteen different silhouettes.
    const grid = S.FRAMES[n];
    const row = Math.min(S.SPR_H - 1, Math.max(0, g.row));
    let ink = 0;
    for (let x = 0; x < S.SPR_W; x++) if (grid[row][x]) ink++;
    if (!ink) bad.push(`${n}: row ${g.row} has no ink -- the glint is off the sprite`);
    else {
      // ...and near the gem itself, not merely somewhere on that line.
      const near = g.cols.some((c) => {
        for (let d = -3; d <= 3; d++) {
          const x = c + d;
          if (x >= 0 && x < S.SPR_W && grid[row][x]) return true;
        }
        return false;
      });
      if (!near) bad.push(`${n}: no ink within 3px of the gem`);
    }
  }
  if (bad.length) bad.forEach(fail);
  else {
    ok(`crown gems measured per pose, all ${live.length} on the sprite ` +
      `(idle0 row ${gems.idle0.row}, run1 row ${gems.run1.row}, land row ${gems.land.row})`);
  }
}

// --- the shield is the artist's own -------------------------------------------
//
// Nothing is stamped on it any more: this sheet draws the arms itself and at
// thirty-six colours they read. The guard is that the character's palette can actually
// HOLD them -- the previous import snapped this art to a thirteen-colour palette with
// no white in it, and the white charge came out as skin-coloured mush with nothing
// failing.
{
  const whites = Object.values(ART.PAL).filter((h) => {
    const n = parseInt(h.slice(1), 16);
    const [r, g, b] = [(n >> 16) & 255, (n >> 8) & 255, n & 255];
    return r > 200 && g > 200 && b > 200;
  });
  if (!whites.length) fail('the palette has no white -- the shield charge cannot render');
  else ok(`${Object.keys(ART.PAL).length} colours, ${whites.length} of them white enough for the charge`);
}

// --- he never loses his sword or his shield -------------------------------------
//
// Twice now a pose has been picked for its shape and shipped with his hands empty: art
// 4 spent a while as the run cycle's fifth frame, so he threw his weapon away every
// fifth stride, and then as the fast fall. Only the death plunge is allowed to disarm
// him, and that one is drawn with his crown coming off too.
{
  const bad = S.NAMES.filter((n) => S.UNARMED_ART.has(S.POSE_ART[n]) && !S.UNARMED_OK.has(n));
  if (bad.length) {
    fail(`${bad.join(', ')} use art he is UNARMED in -- no sword, no shield`);
  } else {
    const used = S.NAMES.filter((n) => S.UNARMED_ART.has(S.POSE_ART[n]));
    ok(`armed in every pose but ${used.join(', ') || 'none'}`);
  }
}

// --- the shield is on a SHIELD --------------------------------------------------
//
// The game does not paint shields any more: this sheet is drawn with the arms of the Grand
// Duchy already on the shield in his hand, in every pose. What is still worth asserting is
// that the shield is THERE -- and, just as much, that it is where a shield is.
//
// Both halves have been wrong. A sheet shipped with a pose whose hands were empty, twice.
// And the old stamper, which found the shield by colour, found his BEARD instead on three
// cells and stamped a coat of arms over his face; no render caught it, because at 1x a
// small red shape in roughly the right place reads as a shield wherever it is.
//
// Two cells have no shield in them and that is the drawing, not a fault: curled into a
// somersault he has it tucked behind him, and the upper half of the parts bin is a torso,
// a head and three arms.
{
  const SF = await import('./shieldfind.mjs');
  SF.resolve(ART.PAL);
  const NO_SHIELD = new Set([13, 16]);            // the somersault, the upper parts bin
  const wrong = [];
  ART.FRAMES.forEach((frame, i) => {
    const face = SF.shieldFace(frame, ART.SPR_W);
    if (NO_SHIELD.has(i) && face) wrong.push(`cell ${i} should have no shield, one was found`);
    if (!NO_SHIELD.has(i) && !face) wrong.push(`cell ${i} carries a shield and none was found`);
  });
  if (wrong.length) wrong.forEach(fail);
  else ok(`${ART.FRAMES.length - NO_SHIELD.size} of ${ART.FRAMES.length} cells carry the arms`);
}

// --- he comes apart into DRAWN pieces ------------------------------------------
//
// The renderer used to cut a whole body into six rectangles, a partition that had to be
// validated pixel by pixel and re-derived for every new sheet. This one draws him in
// bits, so the check is simply that those frames exist and are not the intact body.
{
  const parts = ['parts0', 'parts1'];
  const missing = parts.filter((n) => !NAMES.includes(n));
  if (missing.length) fail(`the splat needs ${missing.join(', ')}`);
  else {
    const same = parts.filter((n) => JSON.stringify(S.FRAMES[n]) === JSON.stringify(S.FRAMES.dazed));
    if (same.length) fail(`${same.join(', ')} is the intact body, not pieces`);
    else ok(`${parts.length} drawn splat frames, neither one the whole man`);
  }
}

// --- no holes through him -------------------------------------------------------
//
// The front-facing idle imported with a hole through his armour down BOTH sides of the
// tabard, and the game drew the backdrop through him. Nothing else caught it, because a
// hole is not missing art -- the art is all there in the sheet -- it is the importer's
// background test deciding that the darkest steel in the shadow under his pauldrons was
// backdrop. The sheet is on navy; a per-channel tolerance around a dark navy contains
// every dark colour there is, and the flood fill from the border walked in through the
// outline and down both flanks. The importer now also requires the backdrop's HUE
// (--bgchroma, see tools/import-sprite.mjs), because shadowed steel is grey and the
// backdrop is blue however dark either gets.
//
// Counted as transparent pixels the border cannot reach. A real gap between an arm and
// the body can be enclosed too, so a handful is allowed; the leak that shipped was 181 in
// one pose and 243 in another.
// The same leak was in two of the companions -- the archer's and the hooded king's sheets
// are on navy too, and the king's robe is near-black -- so they are held to it as well.
function enclosedHoles(rows, W, H) {
  const solid = (x, y) => { const c = (rows[y] || '')[x]; return !!c && c !== '.'; };
  const seen = new Uint8Array(W * H);
  const st = [];
  for (let x = 0; x < W; x++) st.push(x, 0, x, H - 1);
  for (let y = 0; y < H; y++) st.push(0, y, W - 1, y);
  while (st.length) {
    const y = st.pop(), x = st.pop();
    if (x < 0 || y < 0 || x >= W || y >= H) continue;
    const i = y * W + x;
    if (seen[i] || solid(x, y)) continue;
    seen[i] = 1;
    st.push(x + 1, y, x - 1, y, x, y + 1, x, y - 1);
  }
  let holes = 0;
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) if (!solid(x, y) && !seen[y * W + x]) holes++;
  return holes;
}
{
  const HOLE_MAX = 20;
  const sheets = [['duke', ART]];
  for (const id of ['pilgrim', 'archer', 'delver', 'ranger', 'halfling', 'maiden']) {
    sheets.push([id, await import(`../src/render/companions/${id}.js`)]);
  }
  const worst = [];
  for (const [who, A] of sheets) {
    // Minus what the importer opened ON PURPOSE (--open: the inside of the archer's bow),
    // which it counts per frame into OPENED. Only a hole nobody meant is left to fail.
    A.FRAMES.forEach((rows, ci) => worst.push({
      who, ci, holes: enclosedHoles(rows, A.SPR_W, A.SPR_H) - ((A.OPENED && A.OPENED[ci]) || 0),
    }));
  }
  const over = worst.filter((w) => w.holes > HOLE_MAX);
  if (over.length) {
    fail(`see-through art: ${over.map((w) => `${w.who} cell ${w.ci} has ${w.holes}`).join(', ')} ` +
      `enclosed transparent pixels (max ${HOLE_MAX}) -- re-import with --bgchroma`);
  } else {
    const m = worst.reduce((a, b) => (b.holes > a.holes ? b : a));
    ok(`no holes through anyone: worst is ${m.who} cell ${m.ci}, ${m.holes} enclosed transparent pixels`);
  }
}

// --- what is still a placeholder ------------------------------------------------
//
// Not a failure. It is printed every run so the gap between what the game draws and
// what has actually been drawn cannot quietly become permanent.
if (S.DERIVED.length) {
  console.log(`\n  ${S.DERIVED.length} of ${NAMES.length} poses are DERIVED placeholders, not real art:`);
  console.log(`    ${S.DERIVED.join(' ')}`);
  console.log('    see docs/ART-BRIEF.md');
}

console.log(`\n  RESULT: ${bad ? `FAIL - ${bad} problem(s)` : 'PASS'}`);
process.exit(bad ? 1 : 0);
